processed 21 tasks

init:
A: object(0,0)

task 1 'publish'. lines 6-19:
created: object(1,0), object(1,1)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 6315600,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2 'create-checkpoint'. lines 21-21:
Checkpoint created: 1

task 3 'run-graphql'. lines 23-202:
Response: {
  "data": {
    "transactionBlocks": {
      "nodes": [
        {
          "digest": "zoCFh6rD2S4Kite4mzvjmjVQ15mvTn2gEW9ZHukkXnQ",
          "sender": {
            "address": "0xfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e"
          },
          "signatures": [
            "AAuTxso7l8F8hDktxaRyNpMZzBAQn7onJ/ZBat5ioS+o03N11HrR9oUJG3P8phUPvF+uo/bt7N58NLwYCZpYVwt/UUY663bYjcm3XmNyULIgxJz1t5Z9vxfB+fp8WUoJKA=="
          ],
          "gasInput": {
            "gasSponsor": {
              "address": "0xfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e"
            },
            "gasPayment": {
              "nodes": [
                {
                  "address": "0x834050a7a49e9c7b7c2af4b98bdda012ca9e356d65c274266071e613f0530ffc"
                }
              ]
            },
            "gasPrice": "1000",
            "gasBudget": "5000000000"
          },
          "kind": {
            "__typename": "ProgrammableTransactionBlock",
            "inputs": {
              "edges": [
                {
                  "cursor": "eyJpIjowLCJjIjoxfQ",
                  "node": {
                    "__typename": "Pure",
                    "bytes": "/MyaQhu7E8GmahqpjwrXUCnt6UhXd5xpFbRPlAaLkh4="
                  }
                }
              ]
            },
            "transactions": {
              "edges": [
                {
                  "cursor": "eyJpIjowLCJjIjoxfQ",
                  "node": {
                    "__typename": "PublishTransaction",
                    "modules": [
                      "oRzrCwYAAAAIAQAGAgYMAxIKBRwRBy0wCF1ACp0BCQymAQ8ABAEGAQcAAAwAAQIEAAIBAgAABQABAAEFAwQAAgoDBwgCAQgAAAEHCAIBCAEDRm9vCVR4Q29udGV4dANVSUQCaWQBbQNuZXcGb2JqZWN0CnR4X2NvbnRleHQCeHMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAICAwgBCAoDAAEAAAIFCwERAQsAEgACAA=="
                    ],
                    "dependencies": [
                      "0x0000000000000000000000000000000000000000000000000000000000000001",
                      "0x0000000000000000000000000000000000000000000000000000000000000002"
                    ]
                  }
                },
                {
                  "cursor": "eyJpIjoxLCJjIjoxfQ",
                  "node": {
                    "__typename": "TransferObjectsTransaction",
                    "inputs": [
                      {
                        "__typename": "Result",
                        "cmd": 0,
                        "ix": null
                      }
                    ],
                    "address": {
                      "__typename": "Input",
                      "ix": 0
                    }
                  }
                }
              ]
            }
          },
          "effects": {
            "status": "SUCCESS",
            "errors": null,
            "lamportVersion": 2,
            "dependencies": {
              "nodes": [
                {
                  "digest": "22p5xqu5gpAuhfrfXaafxS4BCXZ8Q8B4GSe4h4quNqVJ"
                }
              ]
            },
            "balanceChanges": {
              "nodes": [
                {
                  "owner": {
                    "address": "0xfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e"
                  },
                  "amount": "-7315600",
                  "coinType": {
                    "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::sui::SUI"
                  }
                }
              ]
            },
            "objectChanges": {
              "nodes": [
                {
                  "address": "0x441d3df15085f17822d9b3d4c69af4e7319d8790358f08ae552f887d7744b42f",
                  "idCreated": true,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x441d3df15085f17822d9b3d4c69af4e7319d8790358f08ae552f887d7744b42f",
                    "digest": "42ovELTtRxhKG5XG9y5AbXpL3PgzbFt62xKHJ3R1vkVg"
                  }
                },
                {
                  "address": "0x5ccb80bc887c200ebd3fcb8a5a062fdb1512eebe29c92c9dadcc3b35e3f2e7e8",
                  "idCreated": true,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x5ccb80bc887c200ebd3fcb8a5a062fdb1512eebe29c92c9dadcc3b35e3f2e7e8",
                    "digest": "8sarX6xocSrKQPkVouxJCPtZL3zqemvZe354u8vh2EwN"
                  }
                },
                {
                  "address": "0x834050a7a49e9c7b7c2af4b98bdda012ca9e356d65c274266071e613f0530ffc",
                  "idCreated": false,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x834050a7a49e9c7b7c2af4b98bdda012ca9e356d65c274266071e613f0530ffc",
                    "digest": "2J12cZjMYgtBNe3Ht2UENZKpoSary6KVWnL889mLtRYE"
                  }
                }
              ]
            },
            "gasEffects": {
              "gasObject": {
                "address": "0x834050a7a49e9c7b7c2af4b98bdda012ca9e356d65c274266071e613f0530ffc"
              },
              "gasSummary": {
                "computationCost": "1000000",
                "storageCost": "6315600",
                "storageRebate": "0",
                "nonRefundableStorageFee": "0"
              }
            },
            "timestamp": "1970-01-01T00:00:00Z",
            "epoch": {
              "epochId": 0
            },
            "checkpoint": {
              "sequenceNumber": 1
            },
            "transactionBlock": {
              "digest": "zoCFh6rD2S4Kite4mzvjmjVQ15mvTn2gEW9ZHukkXnQ"
            }
          },
          "expiration": null
        }
      ]
    }
  }
}

task 4 'upgrade'. lines 204-222:
created: object(4,0)
mutated: object(0,0), object(1,1)
gas summary: computation_cost: 1000000, storage_cost: 6589200,  storage_rebate: 2595780, non_refundable_storage_fee: 26220

task 5 'create-checkpoint'. lines 224-224:
Checkpoint created: 2

task 6 'run-graphql'. lines 226-405:
Response: {
  "data": {
    "transactionBlocks": {
      "nodes": [
        {
          "digest": "9txmLXLcvpBL1kV5RQ1h3ehbyJniQaxL2NsLABuQeHFK",
          "sender": {
            "address": "0xfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e"
          },
          "signatures": [
            "AEHHn6jtScdntO3EGh7JyTiwwuDohqRoWWSppNSpgw378vcEhcSu7IL9+4eIXGkvMlGyEaXdxO4k2pDtFz3mBAJ/UUY663bYjcm3XmNyULIgxJz1t5Z9vxfB+fp8WUoJKA=="
          ],
          "gasInput": {
            "gasSponsor": {
              "address": "0xfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e"
            },
            "gasPayment": {
              "nodes": [
                {
                  "address": "0x834050a7a49e9c7b7c2af4b98bdda012ca9e356d65c274266071e613f0530ffc"
                }
              ]
            },
            "gasPrice": "1000",
            "gasBudget": "5000000000"
          },
          "kind": {
            "__typename": "ProgrammableTransactionBlock",
            "inputs": {
              "edges": [
                {
                  "cursor": "eyJpIjowLCJjIjoyfQ",
                  "node": {
                    "__typename": "OwnedOrImmutable",
                    "address": "0x441d3df15085f17822d9b3d4c69af4e7319d8790358f08ae552f887d7744b42f",
                    "version": 2,
                    "digest": "42ovELTtRxhKG5XG9y5AbXpL3PgzbFt62xKHJ3R1vkVg",
                    "object": {
                      "address": "0x441d3df15085f17822d9b3d4c69af4e7319d8790358f08ae552f887d7744b42f",
                      "version": 2,
                      "digest": "42ovELTtRxhKG5XG9y5AbXpL3PgzbFt62xKHJ3R1vkVg",
                      "asMoveObject": {
                        "contents": {
                          "type": {
                            "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::package::UpgradeCap"
                          },
                          "json": {
                            "id": "0x441d3df15085f17822d9b3d4c69af4e7319d8790358f08ae552f887d7744b42f",
                            "package": "0x5ccb80bc887c200ebd3fcb8a5a062fdb1512eebe29c92c9dadcc3b35e3f2e7e8",
                            "version": "1",
                            "policy": 0
                          }
                        }
                      }
                    }
                  }
                },
                {
                  "cursor": "eyJpIjoxLCJjIjoyfQ",
                  "node": {
                    "__typename": "Pure",
                    "bytes": "AA=="
                  }
                },
                {
                  "cursor": "eyJpIjoyLCJjIjoyfQ",
                  "node": {
                    "__typename": "Pure",
                    "bytes": "IKtSxFg0BLyRn8vrtIRqeqpsihVPvPFxPFBg5s0K+UqS"
                  }
                }
              ]
            },
            "transactions": {
              "edges": [
                {
                  "cursor": "eyJpIjowLCJjIjoyfQ",
                  "node": {
                    "__typename": "MoveCallTransaction",
                    "package": "0x0000000000000000000000000000000000000000000000000000000000000002",
                    "module": "package",
                    "functionName": "authorize_upgrade",
                    "typeArguments": [],
                    "arguments": [
                      {
                        "__typename": "Input",
                        "ix": 0
                      },
                      {
                        "__typename": "Input",
                        "ix": 1
                      },
                      {
                        "__typename": "Input",
                        "ix": 2
                      }
                    ],
                    "function": {
                      "isEntry": false,
                      "typeParameters": [],
                      "parameters": [
                        {
                          "repr": "&mut 0x0000000000000000000000000000000000000000000000000000000000000002::package::UpgradeCap"
                        },
                        {
                          "repr": "u8"
                        },
                        {
                          "repr": "vector<u8>"
                        }
                      ],
                      "return": [
                        {
                          "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::package::UpgradeTicket"
                        }
                      ]
                    }
                  }
                },
                {
                  "cursor": "eyJpIjoxLCJjIjoyfQ",
                  "node": {
                    "__typename": "UpgradeTransaction",
                    "modules": [
                      "oRzrCwYAAAAIAQAGAgYMAxIUBSYRBzc8CHNACrMBCQy8AR0ABgEIAQkAAAwAAQIEAAIBAgAABwABAAADAQIAAQQEAgABBwMEAAIKAwcIAgEIAAABBwgCAQgBA0ZvbwlUeENvbnRleHQDVUlEBGJ1cm4GZGVsZXRlAmlkAW0DbmV3Bm9iamVjdAp0eF9jb250ZXh0AnhzAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgACAgUIAQoKAwABAAACBQsBEQMLABIAAgEBAAACBQsAEwABEQICAA=="
                    ],
                    "dependencies": [
                      "0x0000000000000000000000000000000000000000000000000000000000000001",
                      "0x0000000000000000000000000000000000000000000000000000000000000002"
                    ],
                    "currentPackage": "0x5ccb80bc887c200ebd3fcb8a5a062fdb1512eebe29c92c9dadcc3b35e3f2e7e8",
                    "upgradeTicket": {
                      "__typename": "Result",
                      "cmd": 0,
                      "ix": null
                    }
                  }
                },
                {
                  "cursor": "eyJpIjoyLCJjIjoyfQ",
                  "node": {
                    "__typename": "MoveCallTransaction",
                    "package": "0x0000000000000000000000000000000000000000000000000000000000000002",
                    "module": "package",
                    "functionName": "commit_upgrade",
                    "typeArguments": [],
                    "arguments": [
                      {
                        "__typename": "Input",
                        "ix": 0
                      },
                      {
                        "__typename": "Result",
                        "cmd": 1,
                        "ix": null
                      }
                    ],
                    "function": {
                      "isEntry": false,
                      "typeParameters": [],
                      "parameters": [
                        {
                          "repr": "&mut 0x0000000000000000000000000000000000000000000000000000000000000002::package::UpgradeCap"
                        },
                        {
                          "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::package::UpgradeReceipt"
                        }
                      ],
                      "return": []
                    }
                  }
                }
              ]
            }
          },
          "effects": {
            "status": "SUCCESS",
            "errors": null,
            "lamportVersion": 3,
            "dependencies": {
              "nodes": [
                {
                  "digest": "zoCFh6rD2S4Kite4mzvjmjVQ15mvTn2gEW9ZHukkXnQ"
                },
                {
                  "digest": "22p5xqu5gpAuhfrfXaafxS4BCXZ8Q8B4GSe4h4quNqVJ"
                }
              ]
            },
            "balanceChanges": {
              "nodes": [
                {
                  "owner": {
                    "address": "0xfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e"
                  },
                  "amount": "-4993420",
                  "coinType": {
                    "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::sui::SUI"
                  }
                }
              ]
            },
            "objectChanges": {
              "nodes": [
                {
                  "address": "0x3fc4e44ba9aa4457d12a034d9777c3341636fba734605b3b9b7ebf5eed23c9b5",
                  "idCreated": true,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x3fc4e44ba9aa4457d12a034d9777c3341636fba734605b3b9b7ebf5eed23c9b5",
                    "digest": "7RkoRpkGxy3nz1cLDX6rGJjVWGoNXVe346KA27LzK2Az"
                  }
                },
                {
                  "address": "0x441d3df15085f17822d9b3d4c69af4e7319d8790358f08ae552f887d7744b42f",
                  "idCreated": false,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x441d3df15085f17822d9b3d4c69af4e7319d8790358f08ae552f887d7744b42f",
                    "digest": "GqwnZ9Xfob9FRxhniYK4AjAAqNhq14HsqiodVQ24hyhA"
                  }
                },
                {
                  "address": "0x834050a7a49e9c7b7c2af4b98bdda012ca9e356d65c274266071e613f0530ffc",
                  "idCreated": false,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x834050a7a49e9c7b7c2af4b98bdda012ca9e356d65c274266071e613f0530ffc",
                    "digest": "CihbRNbHPf8crZKuY2ndwcgBsMJdke1iZjvZpRnLQvLR"
                  }
                }
              ]
            },
            "gasEffects": {
              "gasObject": {
                "address": "0x834050a7a49e9c7b7c2af4b98bdda012ca9e356d65c274266071e613f0530ffc"
              },
              "gasSummary": {
                "computationCost": "1000000",
                "storageCost": "6589200",
                "storageRebate": "2595780",
                "nonRefundableStorageFee": "26220"
              }
            },
            "timestamp": "1970-01-01T00:00:00Z",
            "epoch": {
              "epochId": 0
            },
            "checkpoint": {
              "sequenceNumber": 2
            },
            "transactionBlock": {
              "digest": "9txmLXLcvpBL1kV5RQ1h3ehbyJniQaxL2NsLABuQeHFK"
            }
          },
          "expiration": null
        }
      ]
    }
  }
}

task 7 'programmable'. lines 407-410:
created: object(7,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2280000,  storage_rebate: 978120, non_refundable_storage_fee: 9880

task 8 'programmable'. lines 412-421:
created: object(8,0), object(8,1)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 3328800,  storage_rebate: 978120, non_refundable_storage_fee: 9880

task 9 'create-checkpoint'. lines 423-423:
Checkpoint created: 3

task 10 'run-graphql'. lines 425-613:
Response: {
  "data": {
    "transactionBlocks": {
      "nodes": [
        {
          "digest": "83hWwJAnE4wkjTWGD6Jfuwemc84PC7BAib2mqaXgCQ8e",
          "sender": {
            "address": "0xfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e"
          },
          "signatures": [
            "AOZHnKQsnPKH333yRkANSKtJwitaKrKrAA8HtOXFZ7yj+wHOhD1sDLYGN38XaR5kX2YfMH6L4vGRt4UeqYPh/A1/UUY663bYjcm3XmNyULIgxJz1t5Z9vxfB+fp8WUoJKA=="
          ],
          "gasInput": {
            "gasSponsor": {
              "address": "0xfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e"
            },
            "gasPayment": {
              "nodes": [
                {
                  "address": "0x834050a7a49e9c7b7c2af4b98bdda012ca9e356d65c274266071e613f0530ffc"
                }
              ]
            },
            "gasPrice": "1000",
            "gasBudget": "5000000000"
          },
          "kind": {
            "__typename": "ProgrammableTransactionBlock",
            "inputs": {
              "edges": [
                {
                  "cursor": "eyJpIjowLCJjIjozfQ",
                  "node": {
                    "__typename": "Pure",
                    "bytes": "KgAAAAAAAAA="
                  }
                },
                {
                  "cursor": "eyJpIjoxLCJjIjozfQ",
                  "node": {
                    "__typename": "Pure",
                    "bytes": "KwAAAAAAAAA="
                  }
                },
                {
                  "cursor": "eyJpIjoyLCJjIjozfQ",
                  "node": {
                    "__typename": "Pure",
                    "bytes": "6AMAAAAAAAA="
                  }
                },
                {
                  "cursor": "eyJpIjozLCJjIjozfQ",
                  "node": {
                    "__typename": "Pure",
                    "bytes": "/MyaQhu7E8GmahqpjwrXUCnt6UhXd5xpFbRPlAaLkh4="
                  }
                }
              ]
            },
            "transactions": {
              "edges": [
                {
                  "cursor": "eyJpIjowLCJjIjozfQ",
                  "node": {
                    "__typename": "MakeMoveVecTransaction",
                    "type": {
                      "repr": "u64"
                    },
                    "elements": [
                      {
                        "__typename": "Input",
                        "ix": 0
                      },
                      {
                        "__typename": "Input",
                        "ix": 1
                      }
                    ]
                  }
                },
                {
                  "cursor": "eyJpIjoxLCJjIjozfQ",
                  "node": {
                    "__typename": "MakeMoveVecTransaction",
                    "type": {
                      "repr": "u64"
                    },
                    "elements": []
                  }
                },
                {
                  "cursor": "eyJpIjoyLCJjIjozfQ",
                  "node": {
                    "__typename": "SplitCoinsTransaction",
                    "coin": {
                      "__typename": "GasCoin"
                    },
                    "amounts": [
                      {
                        "__typename": "Input",
                        "ix": 2
                      },
                      {
                        "__typename": "Input",
                        "ix": 2
                      }
                    ]
                  }
                },
                {
                  "cursor": "eyJpIjozLCJjIjozfQ",
                  "node": {
                    "__typename": "MoveCallTransaction",
                    "package": "0x3fc4e44ba9aa4457d12a034d9777c3341636fba734605b3b9b7ebf5eed23c9b5",
                    "module": "m",
                    "functionName": "new",
                    "typeArguments": [],
                    "arguments": [
                      {
                        "__typename": "Result",
                        "cmd": 0,
                        "ix": null
                      }
                    ],
                    "function": {
                      "isEntry": false,
                      "typeParameters": [],
                      "parameters": [
                        {
                          "repr": "vector<u64>"
                        },
                        {
                          "repr": "&mut 0x0000000000000000000000000000000000000000000000000000000000000002::tx_context::TxContext"
                        }
                      ],
                      "return": [
                        {
                          "repr": "0x5ccb80bc887c200ebd3fcb8a5a062fdb1512eebe29c92c9dadcc3b35e3f2e7e8::m::Foo"
                        }
                      ]
                    }
                  }
                },
                {
                  "cursor": "eyJpIjo0LCJjIjozfQ",
                  "node": {
                    "__typename": "TransferObjectsTransaction",
                    "inputs": [
                      {
                        "__typename": "Result",
                        "cmd": 3,
                        "ix": null
                      }
                    ],
                    "address": {
                      "__typename": "Input",
                      "ix": 3
                    }
                  }
                },
                {
                  "cursor": "eyJpIjo1LCJjIjozfQ",
                  "node": {
                    "__typename": "MoveCallTransaction",
                    "package": "0x3fc4e44ba9aa4457d12a034d9777c3341636fba734605b3b9b7ebf5eed23c9b5",
                    "module": "m",
                    "functionName": "new",
                    "typeArguments": [],
                    "arguments": [
                      {
                        "__typename": "Result",
                        "cmd": 1,
                        "ix": null
                      }
                    ],
                    "function": {
                      "isEntry": false,
                      "typeParameters": [],
                      "parameters": [
                        {
                          "repr": "vector<u64>"
                        },
                        {
                          "repr": "&mut 0x0000000000000000000000000000000000000000000000000000000000000002::tx_context::TxContext"
                        }
                      ],
                      "return": [
                        {
                          "repr": "0x5ccb80bc887c200ebd3fcb8a5a062fdb1512eebe29c92c9dadcc3b35e3f2e7e8::m::Foo"
                        }
                      ]
                    }
                  }
                },
                {
                  "cursor": "eyJpIjo2LCJjIjozfQ",
                  "node": {
                    "__typename": "MoveCallTransaction",
                    "package": "0x3fc4e44ba9aa4457d12a034d9777c3341636fba734605b3b9b7ebf5eed23c9b5",
                    "module": "m",
                    "functionName": "burn",
                    "typeArguments": [],
                    "arguments": [
                      {
                        "__typename": "Result",
                        "cmd": 5,
                        "ix": null
                      }
                    ],
                    "function": {
                      "isEntry": false,
                      "typeParameters": [],
                      "parameters": [
                        {
                          "repr": "0x5ccb80bc887c200ebd3fcb8a5a062fdb1512eebe29c92c9dadcc3b35e3f2e7e8::m::Foo"
                        }
                      ],
                      "return": []
                    }
                  }
                },
                {
                  "cursor": "eyJpIjo3LCJjIjozfQ",
                  "node": {
                    "__typename": "MergeCoinsTransaction",
                    "coin": {
                      "__typename": "Result",
                      "cmd": 2,
                      "ix": 0
                    },
                    "coins": [
                      {
                        "__typename": "Result",
                        "cmd": 2,
                        "ix": 1
                      }
                    ]
                  }
                },
                {
                  "cursor": "eyJpIjo4LCJjIjozfQ",
                  "node": {
                    "__typename": "TransferObjectsTransaction",
                    "inputs": [
                      {
                        "__typename": "Result",
                        "cmd": 2,
                        "ix": 0
                      }
                    ],
                    "address": {
                      "__typename": "Input",
                      "ix": 3
                    }
                  }
                }
              ]
            }
          },
          "effects": {
            "status": "SUCCESS",
            "errors": null,
            "lamportVersion": 5,
            "dependencies": {
              "nodes": [
                {
                  "digest": "4C28AKzp5uDKg8q5SkY9h7Y87NiX8yugFeTce9tEoh5S"
                },
                {
                  "digest": "9txmLXLcvpBL1kV5RQ1h3ehbyJniQaxL2NsLABuQeHFK"
                }
              ]
            },
            "balanceChanges": {
              "nodes": [
                {
                  "owner": {
                    "address": "0xfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e"
                  },
                  "amount": "-3350680",
                  "coinType": {
                    "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::sui::SUI"
                  }
                }
              ]
            },
            "objectChanges": {
              "nodes": [
                {
                  "address": "0x0c90e76fd8a61dbc88346951ca25b7327ba632fd043d0ec6fc187b5b51028d14",
                  "idCreated": true,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x0c90e76fd8a61dbc88346951ca25b7327ba632fd043d0ec6fc187b5b51028d14",
                    "digest": "5C3S55rD7vU2KEwwAuTth7s4cGVAVRBPPqJxw3KKcmsr",
                    "asMoveObject": {
                      "contents": {
                        "type": {
                          "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0x0000000000000000000000000000000000000000000000000000000000000002::sui::SUI>"
                        },
                        "json": {
                          "id": "0x0c90e76fd8a61dbc88346951ca25b7327ba632fd043d0ec6fc187b5b51028d14",
                          "balance": {
                            "value": "2000"
                          }
                        }
                      }
                    }
                  }
                },
                {
                  "address": "0x314a629f04598e2cd5b86fb0600dfafb9e9ec68e5effceb5e72764ae14a1635d",
                  "idCreated": true,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x314a629f04598e2cd5b86fb0600dfafb9e9ec68e5effceb5e72764ae14a1635d",
                    "digest": "G5isBopNor6w8srVES9Z24ZB5qejKVBDNTEVsPAhtnH1",
                    "asMoveObject": {
                      "contents": {
                        "type": {
                          "repr": "0x5ccb80bc887c200ebd3fcb8a5a062fdb1512eebe29c92c9dadcc3b35e3f2e7e8::m::Foo"
                        },
                        "json": {
                          "id": "0x314a629f04598e2cd5b86fb0600dfafb9e9ec68e5effceb5e72764ae14a1635d",
                          "xs": [
                            "42",
                            "43"
                          ]
                        }
                      }
                    }
                  }
                },
                {
                  "address": "0x834050a7a49e9c7b7c2af4b98bdda012ca9e356d65c274266071e613f0530ffc",
                  "idCreated": false,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x834050a7a49e9c7b7c2af4b98bdda012ca9e356d65c274266071e613f0530ffc",
                    "digest": "9My5hXYYpPFLe9hxzteHaToMVvhZ1gzwxEQd5dz72bN3",
                    "asMoveObject": {
                      "contents": {
                        "type": {
                          "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0x0000000000000000000000000000000000000000000000000000000000000002::sui::SUI>"
                        },
                        "json": {
                          "id": "0x834050a7a49e9c7b7c2af4b98bdda012ca9e356d65c274266071e613f0530ffc",
                          "balance": {
                            "value": "299999982036420"
                          }
                        }
                      }
                    }
                  }
                }
              ]
            },
            "gasEffects": {
              "gasObject": {
                "address": "0x834050a7a49e9c7b7c2af4b98bdda012ca9e356d65c274266071e613f0530ffc"
              },
              "gasSummary": {
                "computationCost": "1000000",
                "storageCost": "3328800",
                "storageRebate": "978120",
                "nonRefundableStorageFee": "9880"
              }
            },
            "timestamp": "1970-01-01T00:00:00Z",
            "epoch": {
              "epochId": 0
            },
            "checkpoint": {
              "sequenceNumber": 3
            },
            "transactionBlock": {
              "digest": "83hWwJAnE4wkjTWGD6Jfuwemc84PC7BAib2mqaXgCQ8e"
            }
          },
          "expiration": null
        }
      ]
    }
  }
}

task 11 'programmable'. lines 615-616:
Error: Transaction Effects Status: Unused result without the drop ability. Command result 0, return value 0
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: UnusedValueWithoutDrop { result_idx: 0, secondary_idx: 0 }, source: None, command: None } }

task 12 'create-checkpoint'. lines 618-618:
Checkpoint created: 4

task 13 'run-graphql'. lines 620-799:
Response: {
  "data": {
    "transactionBlocks": {
      "nodes": [
        {
          "digest": "EGks8CiUTco19NrGMEuJmVGVEw6mcL3hy1Nk7dAqUwwK",
          "sender": {
            "address": "0xfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e"
          },
          "signatures": [
            "AGlkGzWsZQ46Pqj5GeLskpy+IbcK1TO1EHTxhXcurcpmwZYtIlCR0NHJtX9C11MB4g4Ti/D6bbTve8r407KgBgV/UUY663bYjcm3XmNyULIgxJz1t5Z9vxfB+fp8WUoJKA=="
          ],
          "gasInput": {
            "gasSponsor": {
              "address": "0xfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e"
            },
            "gasPayment": {
              "nodes": [
                {
                  "address": "0x834050a7a49e9c7b7c2af4b98bdda012ca9e356d65c274266071e613f0530ffc"
                }
              ]
            },
            "gasPrice": "1000",
            "gasBudget": "5000000000"
          },
          "kind": {
            "__typename": "ProgrammableTransactionBlock",
            "inputs": {
              "edges": [
                {
                  "cursor": "eyJpIjowLCJjIjo0fQ",
                  "node": {
                    "__typename": "Pure",
                    "bytes": "6AMAAAAAAAA="
                  }
                }
              ]
            },
            "transactions": {
              "edges": [
                {
                  "cursor": "eyJpIjowLCJjIjo0fQ",
                  "node": {
                    "__typename": "SplitCoinsTransaction",
                    "coin": {
                      "__typename": "GasCoin"
                    },
                    "amounts": [
                      {
                        "__typename": "Input",
                        "ix": 0
                      }
                    ]
                  }
                }
              ]
            }
          },
          "effects": {
            "status": "FAILURE",
            "errors": "Unused result without the drop ability. Command result 0, return value 0",
            "lamportVersion": 6,
            "dependencies": {
              "nodes": [
                {
                  "digest": "83hWwJAnE4wkjTWGD6Jfuwemc84PC7BAib2mqaXgCQ8e"
                }
              ]
            },
            "balanceChanges": {
              "nodes": [
                {
                  "owner": {
                    "address": "0xfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e"
                  },
                  "amount": "-1009880",
                  "coinType": {
                    "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::sui::SUI"
                  }
                }
              ]
            },
            "objectChanges": {
              "nodes": [
                {
                  "address": "0x834050a7a49e9c7b7c2af4b98bdda012ca9e356d65c274266071e613f0530ffc",
                  "idCreated": false,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x834050a7a49e9c7b7c2af4b98bdda012ca9e356d65c274266071e613f0530ffc",
                    "digest": "7znvLvy3XQGWgy2pEKjPuVMsZQ42qeJBpuaGVkVj5fLh"
                  }
                }
              ]
            },
            "gasEffects": {
              "gasObject": {
                "address": "0x834050a7a49e9c7b7c2af4b98bdda012ca9e356d65c274266071e613f0530ffc"
              },
              "gasSummary": {
                "computationCost": "1000000",
                "storageCost": "988000",
                "storageRebate": "978120",
                "nonRefundableStorageFee": "9880"
              }
            },
            "timestamp": "1970-01-01T00:00:00Z",
            "epoch": {
              "epochId": 0
            },
            "checkpoint": {
              "sequenceNumber": 4
            },
            "transactionBlock": {
              "digest": "EGks8CiUTco19NrGMEuJmVGVEw6mcL3hy1Nk7dAqUwwK"
            }
          },
          "expiration": null
        }
      ]
    }
  }
}

task 14 'run-graphql'. lines 801-811:
Response: {
  "data": {
    "transactionBlocks": {
      "edges": [
        {
          "cursor": "eyJjIjo0LCJ0IjowLCJ0YyI6MH0",
          "node": {
            "kind": {
              "__typename": "GenesisTransaction"
            }
          }
        },
        {
          "cursor": "eyJjIjo0LCJ0IjoxLCJ0YyI6MX0",
          "node": {
            "kind": {
              "__typename": "ProgrammableTransactionBlock"
            }
          }
        },
        {
          "cursor": "eyJjIjo0LCJ0IjoyLCJ0YyI6Mn0",
          "node": {
            "kind": {
              "__typename": "ProgrammableTransactionBlock"
            }
          }
        },
        {
          "cursor": "eyJjIjo0LCJ0IjozLCJ0YyI6M30",
          "node": {
            "kind": {
              "__typename": "ProgrammableTransactionBlock"
            }
          }
        },
        {
          "cursor": "eyJjIjo0LCJ0Ijo0LCJ0YyI6M30",
          "node": {
            "kind": {
              "__typename": "ProgrammableTransactionBlock"
            }
          }
        },
        {
          "cursor": "eyJjIjo0LCJ0Ijo1LCJ0YyI6NH0",
          "node": {
            "kind": {
              "__typename": "ProgrammableTransactionBlock"
            }
          }
        }
      ]
    }
  }
}

task 15 'run-graphql'. lines 813-823:
Response: {
  "data": {
    "transactionBlocks": {
      "edges": [
        {
          "cursor": "eyJjIjo0LCJ0IjowLCJ0YyI6MH0",
          "node": {
            "kind": {
              "__typename": "GenesisTransaction"
            }
          }
        }
      ]
    }
  }
}

task 16 'run-graphql'. lines 825-835:
Response: {
  "data": {
    "transactionBlocks": {
      "edges": [
        {
          "cursor": "eyJjIjo0LCJ0IjoxLCJ0YyI6MX0",
          "node": {
            "kind": {
              "__typename": "ProgrammableTransactionBlock"
            }
          }
        },
        {
          "cursor": "eyJjIjo0LCJ0IjoyLCJ0YyI6Mn0",
          "node": {
            "kind": {
              "__typename": "ProgrammableTransactionBlock"
            }
          }
        },
        {
          "cursor": "eyJjIjo0LCJ0IjozLCJ0YyI6M30",
          "node": {
            "kind": {
              "__typename": "ProgrammableTransactionBlock"
            }
          }
        },
        {
          "cursor": "eyJjIjo0LCJ0Ijo0LCJ0YyI6M30",
          "node": {
            "kind": {
              "__typename": "ProgrammableTransactionBlock"
            }
          }
        },
        {
          "cursor": "eyJjIjo0LCJ0Ijo1LCJ0YyI6NH0",
          "node": {
            "kind": {
              "__typename": "ProgrammableTransactionBlock"
            }
          }
        }
      ]
    }
  }
}

task 17 'run-graphql'. lines 837-844:
Response: {
  "data": {
    "address": {
      "transactionBlocks": {
        "nodes": []
      }
    }
  }
}

task 18 'run-graphql'. lines 846-851:
Response: {
  "data": {
    "transactionBlocks": {
      "edges": [
        {
          "cursor": "eyJjIjo0LCJ0IjoyLCJ0YyI6Mn0"
        },
        {
          "cursor": "eyJjIjo0LCJ0IjozLCJ0YyI6M30"
        }
      ]
    }
  }
}

task 19 'run-graphql'. lines 853-858:
Response: {
  "data": {
    "transactionBlocks": {
      "edges": [
        {
          "cursor": "eyJjIjo0LCJ0IjozLCJ0YyI6M30"
        },
        {
          "cursor": "eyJjIjo0LCJ0Ijo0LCJ0YyI6M30"
        }
      ]
    }
  }
}

task 20 'run-graphql'. lines 860-870:
Response: {
  "data": {
    "transactionBlocks": {
      "edges": [
        {
          "cursor": "eyJjIjo0LCJ0IjozLCJ0YyI6M30"
        }
      ]
    }
  }
}
