processed 21 tasks

init:
A: object(0,0), B: object(0,1)

task 1 'publish'. lines 12-41:
created: object(1,0), object(1,1), object(1,2), object(1,3), object(1,4), object(1,5)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 15663600,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2 'create-checkpoint'. lines 43-43:
Checkpoint created: 1

task 3 'programmable'. lines 45-47:
mutated: object(0,0), object(1,1), object(1,5)
gas summary: computation_cost: 1000000, storage_cost: 4012800,  storage_rebate: 3972672, non_refundable_storage_fee: 40128

task 4 'create-checkpoint'. lines 49-49:
Checkpoint created: 2

task 5 'run-graphql'. lines 51-92:
Response: {
  "data": {
    "queryCoinsAtLatest": {
      "edges": [
        {
          "cursor": "IG+esQ8SQKQ9bGw1UUhWCIiFX96SFZng3JNm9E7cJMQ1AgAAAAAAAAA=",
          "node": {
            "consistentStateForEachCoin": {
              "owner": {
                "address": "0xfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e",
                "coins": {
                  "edges": [
                    {
                      "cursor": "IG+esQ8SQKQ9bGw1UUhWCIiFX96SFZng3JNm9E7cJMQ1AgAAAAAAAAA=",
                      "node": {
                        "contents": {
                          "json": {
                            "id": "0x6f9eb10f1240a43d6c6c355148560888855fde921599e0dc9366f44edc24c435",
                            "balance": {
                              "value": "100200"
                            }
                          }
                        }
                      }
                    },
                    {
                      "cursor": "IITfFVGmxZs+NK+VjUM6/xoHxrEX+tGb9YzcglAamK6XAgAAAAAAAAA=",
                      "node": {
                        "contents": {
                          "json": {
                            "id": "0x84df1551a6c59b3e34af958d433aff1a07c6b117fad19bf58cdc82501a98ae97",
                            "balance": {
                              "value": "300"
                            }
                          }
                        }
                      }
                    },
                    {
                      "cursor": "ILH5ELwvLuyhDHZe2OFjMorl6YZemQSIoNTuhFd54lc8AgAAAAAAAAA=",
                      "node": {
                        "contents": {
                          "json": {
                            "id": "0xb1f910bc2f2eeca10c765ed8e163328ae5e9865e990488a0d4ee845779e2573c",
                            "balance": {
                              "value": "100"
                            }
                          }
                        }
                      }
                    }
                  ]
                }
              }
            },
            "contents": {
              "json": {
                "id": "0x6f9eb10f1240a43d6c6c355148560888855fde921599e0dc9366f44edc24c435",
                "balance": {
                  "value": "100200"
                }
              }
            }
          }
        },
        {
          "cursor": "IITfFVGmxZs+NK+VjUM6/xoHxrEX+tGb9YzcglAamK6XAgAAAAAAAAA=",
          "node": {
            "consistentStateForEachCoin": {
              "owner": {
                "address": "0xfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e",
                "coins": {
                  "edges": [
                    {
                      "cursor": "IG+esQ8SQKQ9bGw1UUhWCIiFX96SFZng3JNm9E7cJMQ1AgAAAAAAAAA=",
                      "node": {
                        "contents": {
                          "json": {
                            "id": "0x6f9eb10f1240a43d6c6c355148560888855fde921599e0dc9366f44edc24c435",
                            "balance": {
                              "value": "100200"
                            }
                          }
                        }
                      }
                    },
                    {
                      "cursor": "IITfFVGmxZs+NK+VjUM6/xoHxrEX+tGb9YzcglAamK6XAgAAAAAAAAA=",
                      "node": {
                        "contents": {
                          "json": {
                            "id": "0x84df1551a6c59b3e34af958d433aff1a07c6b117fad19bf58cdc82501a98ae97",
                            "balance": {
                              "value": "300"
                            }
                          }
                        }
                      }
                    },
                    {
                      "cursor": "ILH5ELwvLuyhDHZe2OFjMorl6YZemQSIoNTuhFd54lc8AgAAAAAAAAA=",
                      "node": {
                        "contents": {
                          "json": {
                            "id": "0xb1f910bc2f2eeca10c765ed8e163328ae5e9865e990488a0d4ee845779e2573c",
                            "balance": {
                              "value": "100"
                            }
                          }
                        }
                      }
                    }
                  ]
                }
              }
            },
            "contents": {
              "json": {
                "id": "0x84df1551a6c59b3e34af958d433aff1a07c6b117fad19bf58cdc82501a98ae97",
                "balance": {
                  "value": "300"
                }
              }
            }
          }
        },
        {
          "cursor": "ILH5ELwvLuyhDHZe2OFjMorl6YZemQSIoNTuhFd54lc8AgAAAAAAAAA=",
          "node": {
            "consistentStateForEachCoin": {
              "owner": {
                "address": "0xfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e",
                "coins": {
                  "edges": [
                    {
                      "cursor": "IG+esQ8SQKQ9bGw1UUhWCIiFX96SFZng3JNm9E7cJMQ1AgAAAAAAAAA=",
                      "node": {
                        "contents": {
                          "json": {
                            "id": "0x6f9eb10f1240a43d6c6c355148560888855fde921599e0dc9366f44edc24c435",
                            "balance": {
                              "value": "100200"
                            }
                          }
                        }
                      }
                    },
                    {
                      "cursor": "IITfFVGmxZs+NK+VjUM6/xoHxrEX+tGb9YzcglAamK6XAgAAAAAAAAA=",
                      "node": {
                        "contents": {
                          "json": {
                            "id": "0x84df1551a6c59b3e34af958d433aff1a07c6b117fad19bf58cdc82501a98ae97",
                            "balance": {
                              "value": "300"
                            }
                          }
                        }
                      }
                    },
                    {
                      "cursor": "ILH5ELwvLuyhDHZe2OFjMorl6YZemQSIoNTuhFd54lc8AgAAAAAAAAA=",
                      "node": {
                        "contents": {
                          "json": {
                            "id": "0xb1f910bc2f2eeca10c765ed8e163328ae5e9865e990488a0d4ee845779e2573c",
                            "balance": {
                              "value": "100"
                            }
                          }
                        }
                      }
                    }
                  ]
                }
              }
            },
            "contents": {
              "json": {
                "id": "0xb1f910bc2f2eeca10c765ed8e163328ae5e9865e990488a0d4ee845779e2573c",
                "balance": {
                  "value": "100"
                }
              }
            }
          }
        }
      ]
    },
    "addressCoins": {
      "coins": {
        "edges": [
          {
            "cursor": "IG+esQ8SQKQ9bGw1UUhWCIiFX96SFZng3JNm9E7cJMQ1AgAAAAAAAAA=",
            "node": {
              "contents": {
                "json": {
                  "id": "0x6f9eb10f1240a43d6c6c355148560888855fde921599e0dc9366f44edc24c435",
                  "balance": {
                    "value": "100200"
                  }
                }
              }
            }
          },
          {
            "cursor": "IITfFVGmxZs+NK+VjUM6/xoHxrEX+tGb9YzcglAamK6XAgAAAAAAAAA=",
            "node": {
              "contents": {
                "json": {
                  "id": "0x84df1551a6c59b3e34af958d433aff1a07c6b117fad19bf58cdc82501a98ae97",
                  "balance": {
                    "value": "300"
                  }
                }
              }
            }
          },
          {
            "cursor": "ILH5ELwvLuyhDHZe2OFjMorl6YZemQSIoNTuhFd54lc8AgAAAAAAAAA=",
            "node": {
              "contents": {
                "json": {
                  "id": "0xb1f910bc2f2eeca10c765ed8e163328ae5e9865e990488a0d4ee845779e2573c",
                  "balance": {
                    "value": "100"
                  }
                }
              }
            }
          }
        ]
      }
    }
  }
}

task 6 'run-graphql'. lines 94-135:
Response: {
  "data": {
    "queryCoinsAtChkpt1": {
      "edges": [
        {
          "cursor": "IG+esQ8SQKQ9bGw1UUhWCIiFX96SFZng3JNm9E7cJMQ1AQAAAAAAAAA=",
          "node": {
            "consistentStateForEachCoin": {
              "owner": {
                "address": "0xfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e",
                "coins": {
                  "edges": [
                    {
                      "cursor": "IG+esQ8SQKQ9bGw1UUhWCIiFX96SFZng3JNm9E7cJMQ1AQAAAAAAAAA=",
                      "node": {
                        "contents": {
                          "json": {
                            "id": "0x6f9eb10f1240a43d6c6c355148560888855fde921599e0dc9366f44edc24c435",
                            "balance": {
                              "value": "200"
                            }
                          }
                        }
                      }
                    },
                    {
                      "cursor": "IITfFVGmxZs+NK+VjUM6/xoHxrEX+tGb9YzcglAamK6XAQAAAAAAAAA=",
                      "node": {
                        "contents": {
                          "json": {
                            "id": "0x84df1551a6c59b3e34af958d433aff1a07c6b117fad19bf58cdc82501a98ae97",
                            "balance": {
                              "value": "300"
                            }
                          }
                        }
                      }
                    },
                    {
                      "cursor": "ILH5ELwvLuyhDHZe2OFjMorl6YZemQSIoNTuhFd54lc8AQAAAAAAAAA=",
                      "node": {
                        "contents": {
                          "json": {
                            "id": "0xb1f910bc2f2eeca10c765ed8e163328ae5e9865e990488a0d4ee845779e2573c",
                            "balance": {
                              "value": "100"
                            }
                          }
                        }
                      }
                    }
                  ]
                }
              }
            },
            "contents": {
              "json": {
                "id": "0x6f9eb10f1240a43d6c6c355148560888855fde921599e0dc9366f44edc24c435",
                "balance": {
                  "value": "200"
                }
              }
            }
          }
        },
        {
          "cursor": "IITfFVGmxZs+NK+VjUM6/xoHxrEX+tGb9YzcglAamK6XAQAAAAAAAAA=",
          "node": {
            "consistentStateForEachCoin": {
              "owner": {
                "address": "0xfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e",
                "coins": {
                  "edges": [
                    {
                      "cursor": "IG+esQ8SQKQ9bGw1UUhWCIiFX96SFZng3JNm9E7cJMQ1AQAAAAAAAAA=",
                      "node": {
                        "contents": {
                          "json": {
                            "id": "0x6f9eb10f1240a43d6c6c355148560888855fde921599e0dc9366f44edc24c435",
                            "balance": {
                              "value": "200"
                            }
                          }
                        }
                      }
                    },
                    {
                      "cursor": "IITfFVGmxZs+NK+VjUM6/xoHxrEX+tGb9YzcglAamK6XAQAAAAAAAAA=",
                      "node": {
                        "contents": {
                          "json": {
                            "id": "0x84df1551a6c59b3e34af958d433aff1a07c6b117fad19bf58cdc82501a98ae97",
                            "balance": {
                              "value": "300"
                            }
                          }
                        }
                      }
                    },
                    {
                      "cursor": "ILH5ELwvLuyhDHZe2OFjMorl6YZemQSIoNTuhFd54lc8AQAAAAAAAAA=",
                      "node": {
                        "contents": {
                          "json": {
                            "id": "0xb1f910bc2f2eeca10c765ed8e163328ae5e9865e990488a0d4ee845779e2573c",
                            "balance": {
                              "value": "100"
                            }
                          }
                        }
                      }
                    }
                  ]
                }
              }
            },
            "contents": {
              "json": {
                "id": "0x84df1551a6c59b3e34af958d433aff1a07c6b117fad19bf58cdc82501a98ae97",
                "balance": {
                  "value": "300"
                }
              }
            }
          }
        }
      ]
    },
    "queryAddressCoinsAtChkpt1": {
      "coins": {
        "edges": [
          {
            "cursor": "IG+esQ8SQKQ9bGw1UUhWCIiFX96SFZng3JNm9E7cJMQ1AQAAAAAAAAA=",
            "node": {
              "contents": {
                "json": {
                  "id": "0x6f9eb10f1240a43d6c6c355148560888855fde921599e0dc9366f44edc24c435",
                  "balance": {
                    "value": "200"
                  }
                }
              }
            }
          },
          {
            "cursor": "IITfFVGmxZs+NK+VjUM6/xoHxrEX+tGb9YzcglAamK6XAQAAAAAAAAA=",
            "node": {
              "contents": {
                "json": {
                  "id": "0x84df1551a6c59b3e34af958d433aff1a07c6b117fad19bf58cdc82501a98ae97",
                  "balance": {
                    "value": "300"
                  }
                }
              }
            }
          }
        ]
      }
    }
  }
}

task 7 'transfer-object'. lines 137-137:
mutated: object(0,0), object(1,2)
gas summary: computation_cost: 1000000, storage_cost: 2310400,  storage_rebate: 2287296, non_refundable_storage_fee: 23104

task 8 'transfer-object'. lines 139-139:
mutated: object(0,0), object(1,3)
gas summary: computation_cost: 1000000, storage_cost: 2310400,  storage_rebate: 2287296, non_refundable_storage_fee: 23104

task 9 'create-checkpoint'. lines 141-141:
Checkpoint created: 3

task 10 'run-graphql'. lines 143-196:
Response: {
  "data": {
    "queryCoins": {
      "edges": [
        {
          "cursor": "IG+esQ8SQKQ9bGw1UUhWCIiFX96SFZng3JNm9E7cJMQ1AwAAAAAAAAA=",
          "node": {
            "owner": {
              "owner": {
                "address": "0xfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e",
                "coins": {
                  "edges": [
                    {
                      "cursor": "IG+esQ8SQKQ9bGw1UUhWCIiFX96SFZng3JNm9E7cJMQ1AwAAAAAAAAA=",
                      "node": {
                        "contents": {
                          "json": {
                            "id": "0x6f9eb10f1240a43d6c6c355148560888855fde921599e0dc9366f44edc24c435",
                            "balance": {
                              "value": "100200"
                            }
                          }
                        }
                      }
                    }
                  ]
                }
              }
            },
            "contents": {
              "json": {
                "id": "0x6f9eb10f1240a43d6c6c355148560888855fde921599e0dc9366f44edc24c435",
                "balance": {
                  "value": "100200"
                }
              }
            }
          }
        },
        {
          "cursor": "IITfFVGmxZs+NK+VjUM6/xoHxrEX+tGb9YzcglAamK6XAwAAAAAAAAA=",
          "node": {
            "owner": {
              "owner": {
                "address": "0xa7b032703878aa74c3126935789fd1d4d7e111d5911b09247d6963061c312b5a",
                "coins": {
                  "edges": [
                    {
                      "cursor": "IITfFVGmxZs+NK+VjUM6/xoHxrEX+tGb9YzcglAamK6XAwAAAAAAAAA=",
                      "node": {
                        "contents": {
                          "json": {
                            "id": "0x84df1551a6c59b3e34af958d433aff1a07c6b117fad19bf58cdc82501a98ae97",
                            "balance": {
                              "value": "300"
                            }
                          }
                        }
                      }
                    },
                    {
                      "cursor": "ILH5ELwvLuyhDHZe2OFjMorl6YZemQSIoNTuhFd54lc8AwAAAAAAAAA=",
                      "node": {
                        "contents": {
                          "json": {
                            "id": "0xb1f910bc2f2eeca10c765ed8e163328ae5e9865e990488a0d4ee845779e2573c",
                            "balance": {
                              "value": "100"
                            }
                          }
                        }
                      }
                    }
                  ]
                }
              }
            },
            "contents": {
              "json": {
                "id": "0x84df1551a6c59b3e34af958d433aff1a07c6b117fad19bf58cdc82501a98ae97",
                "balance": {
                  "value": "300"
                }
              }
            }
          }
        },
        {
          "cursor": "ILH5ELwvLuyhDHZe2OFjMorl6YZemQSIoNTuhFd54lc8AwAAAAAAAAA=",
          "node": {
            "owner": {
              "owner": {
                "address": "0xa7b032703878aa74c3126935789fd1d4d7e111d5911b09247d6963061c312b5a",
                "coins": {
                  "edges": [
                    {
                      "cursor": "IITfFVGmxZs+NK+VjUM6/xoHxrEX+tGb9YzcglAamK6XAwAAAAAAAAA=",
                      "node": {
                        "contents": {
                          "json": {
                            "id": "0x84df1551a6c59b3e34af958d433aff1a07c6b117fad19bf58cdc82501a98ae97",
                            "balance": {
                              "value": "300"
                            }
                          }
                        }
                      }
                    },
                    {
                      "cursor": "ILH5ELwvLuyhDHZe2OFjMorl6YZemQSIoNTuhFd54lc8AwAAAAAAAAA=",
                      "node": {
                        "contents": {
                          "json": {
                            "id": "0xb1f910bc2f2eeca10c765ed8e163328ae5e9865e990488a0d4ee845779e2573c",
                            "balance": {
                              "value": "100"
                            }
                          }
                        }
                      }
                    }
                  ]
                }
              }
            },
            "contents": {
              "json": {
                "id": "0xb1f910bc2f2eeca10c765ed8e163328ae5e9865e990488a0d4ee845779e2573c",
                "balance": {
                  "value": "100"
                }
              }
            }
          }
        }
      ]
    },
    "addressCoinsA": {
      "coins": {
        "edges": [
          {
            "cursor": "IG+esQ8SQKQ9bGw1UUhWCIiFX96SFZng3JNm9E7cJMQ1AwAAAAAAAAA=",
            "node": {
              "contents": {
                "json": {
                  "id": "0x6f9eb10f1240a43d6c6c355148560888855fde921599e0dc9366f44edc24c435",
                  "balance": {
                    "value": "100200"
                  }
                }
              }
            }
          }
        ]
      }
    },
    "addressCoinsB": {
      "coins": {
        "edges": [
          {
            "cursor": "IITfFVGmxZs+NK+VjUM6/xoHxrEX+tGb9YzcglAamK6XAwAAAAAAAAA=",
            "node": {
              "contents": {
                "json": {
                  "id": "0x84df1551a6c59b3e34af958d433aff1a07c6b117fad19bf58cdc82501a98ae97",
                  "balance": {
                    "value": "300"
                  }
                }
              }
            }
          },
          {
            "cursor": "ILH5ELwvLuyhDHZe2OFjMorl6YZemQSIoNTuhFd54lc8AwAAAAAAAAA=",
            "node": {
              "contents": {
                "json": {
                  "id": "0xb1f910bc2f2eeca10c765ed8e163328ae5e9865e990488a0d4ee845779e2573c",
                  "balance": {
                    "value": "100"
                  }
                }
              }
            }
          }
        ]
      }
    }
  }
}

task 12 'create-checkpoint'. lines 200-200:
Checkpoint created: 4

task 14 'create-checkpoint'. lines 204-204:
Checkpoint created: 5

task 16 'create-checkpoint'. lines 208-208:
Checkpoint created: 6

task 17 'run-graphql'. lines 210-251:
Response: {
  "data": {
    "queryCoinsAtChkpt1BeforeSnapshotCatchup": {
      "edges": [
        {
          "cursor": "IG+esQ8SQKQ9bGw1UUhWCIiFX96SFZng3JNm9E7cJMQ1AQAAAAAAAAA=",
          "node": {
            "consistentStateForEachCoin": {
              "owner": {
                "address": "0xfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e",
                "coins": {
                  "edges": [
                    {
                      "cursor": "IG+esQ8SQKQ9bGw1UUhWCIiFX96SFZng3JNm9E7cJMQ1AQAAAAAAAAA=",
                      "node": {
                        "contents": {
                          "json": {
                            "id": "0x6f9eb10f1240a43d6c6c355148560888855fde921599e0dc9366f44edc24c435",
                            "balance": {
                              "value": "200"
                            }
                          }
                        }
                      }
                    },
                    {
                      "cursor": "IITfFVGmxZs+NK+VjUM6/xoHxrEX+tGb9YzcglAamK6XAQAAAAAAAAA=",
                      "node": {
                        "contents": {
                          "json": {
                            "id": "0x84df1551a6c59b3e34af958d433aff1a07c6b117fad19bf58cdc82501a98ae97",
                            "balance": {
                              "value": "300"
                            }
                          }
                        }
                      }
                    },
                    {
                      "cursor": "ILH5ELwvLuyhDHZe2OFjMorl6YZemQSIoNTuhFd54lc8AQAAAAAAAAA=",
                      "node": {
                        "contents": {
                          "json": {
                            "id": "0xb1f910bc2f2eeca10c765ed8e163328ae5e9865e990488a0d4ee845779e2573c",
                            "balance": {
                              "value": "100"
                            }
                          }
                        }
                      }
                    }
                  ]
                }
              }
            },
            "contents": {
              "json": {
                "id": "0x6f9eb10f1240a43d6c6c355148560888855fde921599e0dc9366f44edc24c435",
                "balance": {
                  "value": "200"
                }
              }
            }
          }
        },
        {
          "cursor": "IITfFVGmxZs+NK+VjUM6/xoHxrEX+tGb9YzcglAamK6XAQAAAAAAAAA=",
          "node": {
            "consistentStateForEachCoin": {
              "owner": {
                "address": "0xfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e",
                "coins": {
                  "edges": [
                    {
                      "cursor": "IG+esQ8SQKQ9bGw1UUhWCIiFX96SFZng3JNm9E7cJMQ1AQAAAAAAAAA=",
                      "node": {
                        "contents": {
                          "json": {
                            "id": "0x6f9eb10f1240a43d6c6c355148560888855fde921599e0dc9366f44edc24c435",
                            "balance": {
                              "value": "200"
                            }
                          }
                        }
                      }
                    },
                    {
                      "cursor": "IITfFVGmxZs+NK+VjUM6/xoHxrEX+tGb9YzcglAamK6XAQAAAAAAAAA=",
                      "node": {
                        "contents": {
                          "json": {
                            "id": "0x84df1551a6c59b3e34af958d433aff1a07c6b117fad19bf58cdc82501a98ae97",
                            "balance": {
                              "value": "300"
                            }
                          }
                        }
                      }
                    },
                    {
                      "cursor": "ILH5ELwvLuyhDHZe2OFjMorl6YZemQSIoNTuhFd54lc8AQAAAAAAAAA=",
                      "node": {
                        "contents": {
                          "json": {
                            "id": "0xb1f910bc2f2eeca10c765ed8e163328ae5e9865e990488a0d4ee845779e2573c",
                            "balance": {
                              "value": "100"
                            }
                          }
                        }
                      }
                    }
                  ]
                }
              }
            },
            "contents": {
              "json": {
                "id": "0x84df1551a6c59b3e34af958d433aff1a07c6b117fad19bf58cdc82501a98ae97",
                "balance": {
                  "value": "300"
                }
              }
            }
          }
        }
      ]
    },
    "queryAddressCoinsAtChkpt1BeforeSnapshotCatchup": {
      "coins": {
        "edges": [
          {
            "cursor": "IG+esQ8SQKQ9bGw1UUhWCIiFX96SFZng3JNm9E7cJMQ1AQAAAAAAAAA=",
            "node": {
              "contents": {
                "json": {
                  "id": "0x6f9eb10f1240a43d6c6c355148560888855fde921599e0dc9366f44edc24c435",
                  "balance": {
                    "value": "200"
                  }
                }
              }
            }
          },
          {
            "cursor": "IITfFVGmxZs+NK+VjUM6/xoHxrEX+tGb9YzcglAamK6XAQAAAAAAAAA=",
            "node": {
              "contents": {
                "json": {
                  "id": "0x84df1551a6c59b3e34af958d433aff1a07c6b117fad19bf58cdc82501a98ae97",
                  "balance": {
                    "value": "300"
                  }
                }
              }
            }
          }
        ]
      }
    }
  }
}

task 18 'force-object-snapshot-catchup'. lines 253-253:
Objects snapshot updated to [0 to 4)

task 19 'create-checkpoint'. lines 255-255:
Checkpoint created: 7

task 20 'run-graphql'. lines 257-286:
Response: {
  "data": null,
  "errors": [
    {
      "message": "Requested data is outside the available range",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "queryCoinsAtChkpt1AfterSnapshotCatchup"
      ],
      "extensions": {
        "code": "BAD_USER_INPUT"
      }
    }
  ]
}
