processed 24 tasks

init:
A: object(0,0), B: object(0,1)

task 1 'publish'. lines 15-32:
created: object(1,0)
mutated: object(0,2)
gas summary: computation_cost: 1000000, storage_cost: 5175600,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2 'run'. lines 34-34:
created: object(2,0)
mutated: object(0,2)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 978120, non_refundable_storage_fee: 9880

task 3 'run'. lines 36-36:
created: object(3,0)
mutated: object(0,2)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 978120, non_refundable_storage_fee: 9880

task 4 'create-checkpoint'. lines 38-38:
Checkpoint created: 1

task 5 'run-graphql'. lines 40-68:
Response: {
  "data": {
    "one_of_these_will_yield_an_object": {
      "objects": {
        "nodes": [
          {
            "version": 4,
            "contents": {
              "type": {
                "repr": "0xbb6aa2e85d56cb1c2ed79ab94310af6bf00c1d9b57e14b03c60971b96f70df00::M1::Object"
              },
              "json": {
                "id": "0x8f984b24ba4fc02883a2143e30c2ecb7d30b919de99c35150a7bf7ebc775d9bf",
                "value": "1"
              }
            }
          }
        ]
      }
    },
    "if_the_other_does_not": {
      "nodes": []
    }
  }
}

task 6 'run'. lines 70-70:
created: object(6,0)
mutated: object(0,2)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 978120, non_refundable_storage_fee: 9880

task 7 'run'. lines 72-72:
created: object(7,0)
mutated: object(0,2)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 978120, non_refundable_storage_fee: 9880

task 8 'create-checkpoint'. lines 74-74:
Checkpoint created: 2

task 9 'run-graphql'. lines 76-104:
Response: {
  "data": {
    "paginating_on_checkpoint_1": {
      "objects": {
        "nodes": [
          {
            "version": 4,
            "contents": {
              "type": {
                "repr": "0xbb6aa2e85d56cb1c2ed79ab94310af6bf00c1d9b57e14b03c60971b96f70df00::M1::Object"
              },
              "json": {
                "id": "0x8f984b24ba4fc02883a2143e30c2ecb7d30b919de99c35150a7bf7ebc775d9bf",
                "value": "1"
              }
            }
          }
        ]
      }
    },
    "should_not_have_more_than_one_result": {
      "nodes": []
    }
  }
}

task 10 'run-graphql'. lines 106-121:
Response: {
  "data": {
    "four_objects": {
      "objects": {
        "nodes": [
          {
            "version": 3,
            "contents": {
              "type": {
                "repr": "0xbb6aa2e85d56cb1c2ed79ab94310af6bf00c1d9b57e14b03c60971b96f70df00::M1::Object"
              },
              "json": {
                "id": "0x018441736f972b61660a5db885ea1814b2496ff33600ca304189fd6df5ea4ccf",
                "value": "0"
              }
            }
          },
          {
            "version": 6,
            "contents": {
              "type": {
                "repr": "0xbb6aa2e85d56cb1c2ed79ab94310af6bf00c1d9b57e14b03c60971b96f70df00::M1::Object"
              },
              "json": {
                "id": "0x4d6c6dd1e972374cdad7f2ec692c2b0e19f482a18aeedc7c0a9e7471fff487c9",
                "value": "3"
              }
            }
          },
          {
            "version": 5,
            "contents": {
              "type": {
                "repr": "0xbb6aa2e85d56cb1c2ed79ab94310af6bf00c1d9b57e14b03c60971b96f70df00::M1::Object"
              },
              "json": {
                "id": "0x6d7598ba94bb1aca181ad93c2174cd1efec60c1edafc203272ce89c03d2a5b4b",
                "value": "2"
              }
            }
          },
          {
            "version": 4,
            "contents": {
              "type": {
                "repr": "0xbb6aa2e85d56cb1c2ed79ab94310af6bf00c1d9b57e14b03c60971b96f70df00::M1::Object"
              },
              "json": {
                "id": "0x8f984b24ba4fc02883a2143e30c2ecb7d30b919de99c35150a7bf7ebc775d9bf",
                "value": "1"
              }
            }
          }
        ]
      }
    }
  }
}

task 11 'run-graphql'. lines 123-148:
Response: {
  "data": {
    "objects_at_version": {
      "objects": {
        "nodes": [
          {
            "version": 3,
            "contents": {
              "type": {
                "repr": "0xbb6aa2e85d56cb1c2ed79ab94310af6bf00c1d9b57e14b03c60971b96f70df00::M1::Object"
              },
              "json": {
                "id": "0x018441736f972b61660a5db885ea1814b2496ff33600ca304189fd6df5ea4ccf",
                "value": "0"
              }
            }
          },
          {
            "version": 6,
            "contents": {
              "type": {
                "repr": "0xbb6aa2e85d56cb1c2ed79ab94310af6bf00c1d9b57e14b03c60971b96f70df00::M1::Object"
              },
              "json": {
                "id": "0x4d6c6dd1e972374cdad7f2ec692c2b0e19f482a18aeedc7c0a9e7471fff487c9",
                "value": "3"
              }
            }
          },
          {
            "version": 5,
            "contents": {
              "type": {
                "repr": "0xbb6aa2e85d56cb1c2ed79ab94310af6bf00c1d9b57e14b03c60971b96f70df00::M1::Object"
              },
              "json": {
                "id": "0x6d7598ba94bb1aca181ad93c2174cd1efec60c1edafc203272ce89c03d2a5b4b",
                "value": "2"
              }
            }
          },
          {
            "version": 4,
            "contents": {
              "type": {
                "repr": "0xbb6aa2e85d56cb1c2ed79ab94310af6bf00c1d9b57e14b03c60971b96f70df00::M1::Object"
              },
              "json": {
                "id": "0x8f984b24ba4fc02883a2143e30c2ecb7d30b919de99c35150a7bf7ebc775d9bf",
                "value": "1"
              }
            }
          }
        ]
      }
    }
  }
}

task 12 'programmable'. lines 150-151:
mutated: object(0,0), object(2,0), object(3,0), object(6,0), object(7,0)
gas summary: computation_cost: 1000000, storage_cost: 6247200,  storage_rebate: 5206608, non_refundable_storage_fee: 52592

task 13 'create-checkpoint'. lines 153-153:
Checkpoint created: 3

task 14 'run-graphql'. lines 155-217:
Response: {
  "data": {
    "after_obj_6_0_at_checkpoint_2": {
      "objects": {
        "nodes": [
          {
            "version": 4,
            "contents": {
              "type": {
                "repr": "0xbb6aa2e85d56cb1c2ed79ab94310af6bf00c1d9b57e14b03c60971b96f70df00::M1::Object"
              },
              "json": {
                "id": "0x8f984b24ba4fc02883a2143e30c2ecb7d30b919de99c35150a7bf7ebc775d9bf",
                "value": "1"
              }
            },
            "owner_at_latest_state_has_sui_only": {
              "owner": {
                "objects": {
                  "nodes": [
                    {
                      "version": 3,
                      "contents": {
                        "type": {
                          "repr": "0xbb6aa2e85d56cb1c2ed79ab94310af6bf00c1d9b57e14b03c60971b96f70df00::M1::Object"
                        },
                        "json": {
                          "id": "0x018441736f972b61660a5db885ea1814b2496ff33600ca304189fd6df5ea4ccf",
                          "value": "0"
                        }
                      }
                    },
                    {
                      "version": 6,
                      "contents": {
                        "type": {
                          "repr": "0xbb6aa2e85d56cb1c2ed79ab94310af6bf00c1d9b57e14b03c60971b96f70df00::M1::Object"
                        },
                        "json": {
                          "id": "0x4d6c6dd1e972374cdad7f2ec692c2b0e19f482a18aeedc7c0a9e7471fff487c9",
                          "value": "3"
                        }
                      }
                    },
                    {
                      "version": 5,
                      "contents": {
                        "type": {
                          "repr": "0xbb6aa2e85d56cb1c2ed79ab94310af6bf00c1d9b57e14b03c60971b96f70df00::M1::Object"
                        },
                        "json": {
                          "id": "0x6d7598ba94bb1aca181ad93c2174cd1efec60c1edafc203272ce89c03d2a5b4b",
                          "value": "2"
                        }
                      }
                    },
                    {
                      "version": 4,
                      "contents": {
                        "type": {
                          "repr": "0xbb6aa2e85d56cb1c2ed79ab94310af6bf00c1d9b57e14b03c60971b96f70df00::M1::Object"
                        },
                        "json": {
                          "id": "0x8f984b24ba4fc02883a2143e30c2ecb7d30b919de99c35150a7bf7ebc775d9bf",
                          "value": "1"
                        }
                      }
                    },
                    {
                      "version": 1,
                      "contents": {
                        "type": {
                          "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0x0000000000000000000000000000000000000000000000000000000000000002::sui::SUI>"
                        },
                        "json": {
                          "id": "0x9b428e08aa9b65353e2ffce9231667f43e1bdbac51059739e40443cf1f497d70",
                          "balance": {
                            "value": "300000000000000"
                          }
                        }
                      }
                    }
                  ]
                }
              }
            }
          }
        ]
      }
    },
    "before_obj_6_0_at_checkpoint_2": {
      "nodes": [
        {
          "version": 3,
          "asMoveObject": {
            "contents": {
              "type": {
                "repr": "0xbb6aa2e85d56cb1c2ed79ab94310af6bf00c1d9b57e14b03c60971b96f70df00::M1::Object"
              },
              "json": {
                "id": "0x018441736f972b61660a5db885ea1814b2496ff33600ca304189fd6df5ea4ccf",
                "value": "0"
              }
            },
            "note_that_owner_result_should_reflect_latest_state": {
              "owner": {
                "objects": {
                  "nodes": [
                    {
                      "version": 3,
                      "contents": {
                        "type": {
                          "repr": "0xbb6aa2e85d56cb1c2ed79ab94310af6bf00c1d9b57e14b03c60971b96f70df00::M1::Object"
                        },
                        "json": {
                          "id": "0x018441736f972b61660a5db885ea1814b2496ff33600ca304189fd6df5ea4ccf",
                          "value": "0"
                        }
                      }
                    },
                    {
                      "version": 6,
                      "contents": {
                        "type": {
                          "repr": "0xbb6aa2e85d56cb1c2ed79ab94310af6bf00c1d9b57e14b03c60971b96f70df00::M1::Object"
                        },
                        "json": {
                          "id": "0x4d6c6dd1e972374cdad7f2ec692c2b0e19f482a18aeedc7c0a9e7471fff487c9",
                          "value": "3"
                        }
                      }
                    },
                    {
                      "version": 5,
                      "contents": {
                        "type": {
                          "repr": "0xbb6aa2e85d56cb1c2ed79ab94310af6bf00c1d9b57e14b03c60971b96f70df00::M1::Object"
                        },
                        "json": {
                          "id": "0x6d7598ba94bb1aca181ad93c2174cd1efec60c1edafc203272ce89c03d2a5b4b",
                          "value": "2"
                        }
                      }
                    },
                    {
                      "version": 4,
                      "contents": {
                        "type": {
                          "repr": "0xbb6aa2e85d56cb1c2ed79ab94310af6bf00c1d9b57e14b03c60971b96f70df00::M1::Object"
                        },
                        "json": {
                          "id": "0x8f984b24ba4fc02883a2143e30c2ecb7d30b919de99c35150a7bf7ebc775d9bf",
                          "value": "1"
                        }
                      }
                    },
                    {
                      "version": 1,
                      "contents": {
                        "type": {
                          "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0x0000000000000000000000000000000000000000000000000000000000000002::sui::SUI>"
                        },
                        "json": {
                          "id": "0x9b428e08aa9b65353e2ffce9231667f43e1bdbac51059739e40443cf1f497d70",
                          "balance": {
                            "value": "300000000000000"
                          }
                        }
                      }
                    }
                  ]
                }
              }
            }
          }
        },
        {
          "version": 6,
          "asMoveObject": {
            "contents": {
              "type": {
                "repr": "0xbb6aa2e85d56cb1c2ed79ab94310af6bf00c1d9b57e14b03c60971b96f70df00::M1::Object"
              },
              "json": {
                "id": "0x4d6c6dd1e972374cdad7f2ec692c2b0e19f482a18aeedc7c0a9e7471fff487c9",
                "value": "3"
              }
            },
            "note_that_owner_result_should_reflect_latest_state": {
              "owner": {
                "objects": {
                  "nodes": [
                    {
                      "version": 3,
                      "contents": {
                        "type": {
                          "repr": "0xbb6aa2e85d56cb1c2ed79ab94310af6bf00c1d9b57e14b03c60971b96f70df00::M1::Object"
                        },
                        "json": {
                          "id": "0x018441736f972b61660a5db885ea1814b2496ff33600ca304189fd6df5ea4ccf",
                          "value": "0"
                        }
                      }
                    },
                    {
                      "version": 6,
                      "contents": {
                        "type": {
                          "repr": "0xbb6aa2e85d56cb1c2ed79ab94310af6bf00c1d9b57e14b03c60971b96f70df00::M1::Object"
                        },
                        "json": {
                          "id": "0x4d6c6dd1e972374cdad7f2ec692c2b0e19f482a18aeedc7c0a9e7471fff487c9",
                          "value": "3"
                        }
                      }
                    },
                    {
                      "version": 5,
                      "contents": {
                        "type": {
                          "repr": "0xbb6aa2e85d56cb1c2ed79ab94310af6bf00c1d9b57e14b03c60971b96f70df00::M1::Object"
                        },
                        "json": {
                          "id": "0x6d7598ba94bb1aca181ad93c2174cd1efec60c1edafc203272ce89c03d2a5b4b",
                          "value": "2"
                        }
                      }
                    },
                    {
                      "version": 4,
                      "contents": {
                        "type": {
                          "repr": "0xbb6aa2e85d56cb1c2ed79ab94310af6bf00c1d9b57e14b03c60971b96f70df00::M1::Object"
                        },
                        "json": {
                          "id": "0x8f984b24ba4fc02883a2143e30c2ecb7d30b919de99c35150a7bf7ebc775d9bf",
                          "value": "1"
                        }
                      }
                    },
                    {
                      "version": 1,
                      "contents": {
                        "type": {
                          "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0x0000000000000000000000000000000000000000000000000000000000000002::sui::SUI>"
                        },
                        "json": {
                          "id": "0x9b428e08aa9b65353e2ffce9231667f43e1bdbac51059739e40443cf1f497d70",
                          "balance": {
                            "value": "300000000000000"
                          }
                        }
                      }
                    }
                  ]
                }
              }
            }
          }
        }
      ]
    }
  }
}

task 16 'create-checkpoint'. lines 221-221:
Checkpoint created: 4

task 18 'create-checkpoint'. lines 225-225:
Checkpoint created: 5

task 19 'force-object-snapshot-catchup'. lines 227-227:
Objects snapshot updated to [0 to 4)

task 20 'create-checkpoint'. lines 229-229:
Checkpoint created: 6

task 21 'run-graphql'. lines 231-246:
Response: {
  "data": null,
  "errors": [
    {
      "message": "Requested data is outside the available range",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "before_obj_6_0_at_checkpoint_2"
      ],
      "extensions": {
        "code": "BAD_USER_INPUT"
      }
    }
  ]
}

task 22 'run-graphql'. lines 248-264:
Response: {
  "data": {
    "owned_by_address_b_latest": {
      "objects": {
        "nodes": [
          {
            "version": 7,
            "contents": {
              "type": {
                "repr": "0xbb6aa2e85d56cb1c2ed79ab94310af6bf00c1d9b57e14b03c60971b96f70df00::M1::Object"
              },
              "json": {
                "id": "0x018441736f972b61660a5db885ea1814b2496ff33600ca304189fd6df5ea4ccf",
                "value": "0"
              }
            }
          },
          {
            "version": 7,
            "contents": {
              "type": {
                "repr": "0xbb6aa2e85d56cb1c2ed79ab94310af6bf00c1d9b57e14b03c60971b96f70df00::M1::Object"
              },
              "json": {
                "id": "0x4d6c6dd1e972374cdad7f2ec692c2b0e19f482a18aeedc7c0a9e7471fff487c9",
                "value": "3"
              }
            }
          },
          {
            "version": 7,
            "contents": {
              "type": {
                "repr": "0xbb6aa2e85d56cb1c2ed79ab94310af6bf00c1d9b57e14b03c60971b96f70df00::M1::Object"
              },
              "json": {
                "id": "0x6d7598ba94bb1aca181ad93c2174cd1efec60c1edafc203272ce89c03d2a5b4b",
                "value": "2"
              }
            }
          },
          {
            "version": 7,
            "contents": {
              "type": {
                "repr": "0xbb6aa2e85d56cb1c2ed79ab94310af6bf00c1d9b57e14b03c60971b96f70df00::M1::Object"
              },
              "json": {
                "id": "0x8f984b24ba4fc02883a2143e30c2ecb7d30b919de99c35150a7bf7ebc775d9bf",
                "value": "1"
              }
            }
          }
        ]
      }
    }
  }
}

task 23 'run-graphql'. lines 266-292:
Response: {
  "data": {
    "objects_at_version": {
      "objects": {
        "nodes": [
          {
            "version": 3,
            "contents": {
              "type": {
                "repr": "0xbb6aa2e85d56cb1c2ed79ab94310af6bf00c1d9b57e14b03c60971b96f70df00::M1::Object"
              },
              "json": {
                "id": "0x018441736f972b61660a5db885ea1814b2496ff33600ca304189fd6df5ea4ccf",
                "value": "0"
              }
            }
          },
          {
            "version": 6,
            "contents": {
              "type": {
                "repr": "0xbb6aa2e85d56cb1c2ed79ab94310af6bf00c1d9b57e14b03c60971b96f70df00::M1::Object"
              },
              "json": {
                "id": "0x4d6c6dd1e972374cdad7f2ec692c2b0e19f482a18aeedc7c0a9e7471fff487c9",
                "value": "3"
              }
            }
          },
          {
            "version": 5,
            "contents": {
              "type": {
                "repr": "0xbb6aa2e85d56cb1c2ed79ab94310af6bf00c1d9b57e14b03c60971b96f70df00::M1::Object"
              },
              "json": {
                "id": "0x6d7598ba94bb1aca181ad93c2174cd1efec60c1edafc203272ce89c03d2a5b4b",
                "value": "2"
              }
            }
          },
          {
            "version": 4,
            "contents": {
              "type": {
                "repr": "0xbb6aa2e85d56cb1c2ed79ab94310af6bf00c1d9b57e14b03c60971b96f70df00::M1::Object"
              },
              "json": {
                "id": "0x8f984b24ba4fc02883a2143e30c2ecb7d30b919de99c35150a7bf7ebc775d9bf",
                "value": "1"
              }
            }
          }
        ]
      }
    }
  }
}
