processed 17 tasks

init:
A: object(0,0), B: object(0,1)

task 1 'publish'. lines 17-38:
created: object(1,0)
mutated: object(0,2)
gas summary: computation_cost: 1000000, storage_cost: 5479600,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2 'programmable'. lines 40-41:
created: object(2,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 0, non_refundable_storage_fee: 0

task 3 'create-checkpoint'. lines 43-43:
Checkpoint created: 1

task 4 'programmable'. lines 45-48:
created: object(4,0), object(4,1)
mutated: object(0,0), object(2,0)
gas summary: computation_cost: 1000000, storage_cost: 4932400,  storage_rebate: 2279772, non_refundable_storage_fee: 23028

task 5 'create-checkpoint'. lines 50-50:
Checkpoint created: 2

task 6 'programmable'. lines 52-56:
created: object(6,0), object(6,1), object(6,2)
mutated: object(0,0), object(2,0)
gas summary: computation_cost: 1000000, storage_cost: 6247200,  storage_rebate: 2279772, non_refundable_storage_fee: 23028

task 7 'create-checkpoint'. lines 58-58:
Checkpoint created: 3

task 9 'create-checkpoint'. lines 62-62:
Checkpoint created: 4

task 10 'run-graphql'. lines 64-138:
Response: {
  "data": {
    "address_at_latest_checkpoint_4": {
      "objects": {
        "nodes": [
          {
            "contents": {
              "json": {
                "id": "0x3ac686cdae3a9e3a5b0048844f7a33cc97aa72abe4ad4ad03e8de5b722d1bc33",
                "value": "6"
              },
              "type": {
                "repr": "0x4abd7204bc024fbf9b78296fce94bc2b3ac71edb0f24b0d52d2268974a066316::M1::Object"
              }
            }
          },
          {
            "contents": {
              "json": {
                "id": "0x3ff04c623ee8dda6c2b5c0af65ac248cd07507e92b162c0b8f7702246f6c7bc8",
                "value": "3"
              },
              "type": {
                "repr": "0x4abd7204bc024fbf9b78296fce94bc2b3ac71edb0f24b0d52d2268974a066316::M1::Object"
              }
            }
          },
          {
            "contents": {
              "json": {
                "id": "0x50cf0ec16e23b372376dea614904fd10eda1237c204baf4aac5109d4c8125d63",
                "value": "5"
              },
              "type": {
                "repr": "0x4abd7204bc024fbf9b78296fce94bc2b3ac71edb0f24b0d52d2268974a066316::M1::Object"
              }
            }
          },
          {
            "contents": {
              "json": {
                "id": "0x58262f3e7d94e1cf1c6f77ac4498d2a1704bbde20b0b8f37a723426e43971c6b",
                "value": "4"
              },
              "type": {
                "repr": "0x4abd7204bc024fbf9b78296fce94bc2b3ac71edb0f24b0d52d2268974a066316::M1::Object"
              }
            }
          },
          {
            "contents": {
              "json": {
                "id": "0xa20233cc7036333cec016bdad557d0c2bbc7bc8a5499ad6fedb6f144822fd29c",
                "value": "2"
              },
              "type": {
                "repr": "0x4abd7204bc024fbf9b78296fce94bc2b3ac71edb0f24b0d52d2268974a066316::M1::Object"
              }
            }
          },
          {
            "contents": {
              "json": {
                "id": "0xaf75cbf4e4115f4b723b5304461077b88db33bfff1aa24292c45612322bfd55b",
                "value": "200"
              },
              "type": {
                "repr": "0x4abd7204bc024fbf9b78296fce94bc2b3ac71edb0f24b0d52d2268974a066316::M1::Object"
              }
            }
          }
        ]
      }
    },
    "latest_tx_at_checkpoint_3": {
      "nodes": [
        {
          "sender": {
            "objects_consistent_with_address_at_latest_checkpoint_4": {
              "nodes": [
                {
                  "contents": {
                    "json": {
                      "id": "0x3ac686cdae3a9e3a5b0048844f7a33cc97aa72abe4ad4ad03e8de5b722d1bc33",
                      "value": "6"
                    },
                    "type": {
                      "repr": "0x4abd7204bc024fbf9b78296fce94bc2b3ac71edb0f24b0d52d2268974a066316::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x3ff04c623ee8dda6c2b5c0af65ac248cd07507e92b162c0b8f7702246f6c7bc8",
                      "value": "3"
                    },
                    "type": {
                      "repr": "0x4abd7204bc024fbf9b78296fce94bc2b3ac71edb0f24b0d52d2268974a066316::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x50cf0ec16e23b372376dea614904fd10eda1237c204baf4aac5109d4c8125d63",
                      "value": "5"
                    },
                    "type": {
                      "repr": "0x4abd7204bc024fbf9b78296fce94bc2b3ac71edb0f24b0d52d2268974a066316::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x58262f3e7d94e1cf1c6f77ac4498d2a1704bbde20b0b8f37a723426e43971c6b",
                      "value": "4"
                    },
                    "type": {
                      "repr": "0x4abd7204bc024fbf9b78296fce94bc2b3ac71edb0f24b0d52d2268974a066316::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xa20233cc7036333cec016bdad557d0c2bbc7bc8a5499ad6fedb6f144822fd29c",
                      "value": "2"
                    },
                    "type": {
                      "repr": "0x4abd7204bc024fbf9b78296fce94bc2b3ac71edb0f24b0d52d2268974a066316::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xaf75cbf4e4115f4b723b5304461077b88db33bfff1aa24292c45612322bfd55b",
                      "value": "200"
                    },
                    "type": {
                      "repr": "0x4abd7204bc024fbf9b78296fce94bc2b3ac71edb0f24b0d52d2268974a066316::M1::Object"
                    }
                  }
                }
              ]
            }
          },
          "gasInput": {
            "gasSponsor": {
              "objects": {
                "nodes": [
                  {
                    "contents": {
                      "json": {
                        "id": "0x3ac686cdae3a9e3a5b0048844f7a33cc97aa72abe4ad4ad03e8de5b722d1bc33",
                        "value": "6"
                      },
                      "type": {
                        "repr": "0x4abd7204bc024fbf9b78296fce94bc2b3ac71edb0f24b0d52d2268974a066316::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0x3ff04c623ee8dda6c2b5c0af65ac248cd07507e92b162c0b8f7702246f6c7bc8",
                        "value": "3"
                      },
                      "type": {
                        "repr": "0x4abd7204bc024fbf9b78296fce94bc2b3ac71edb0f24b0d52d2268974a066316::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0x50cf0ec16e23b372376dea614904fd10eda1237c204baf4aac5109d4c8125d63",
                        "value": "5"
                      },
                      "type": {
                        "repr": "0x4abd7204bc024fbf9b78296fce94bc2b3ac71edb0f24b0d52d2268974a066316::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0x58262f3e7d94e1cf1c6f77ac4498d2a1704bbde20b0b8f37a723426e43971c6b",
                        "value": "4"
                      },
                      "type": {
                        "repr": "0x4abd7204bc024fbf9b78296fce94bc2b3ac71edb0f24b0d52d2268974a066316::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0xa20233cc7036333cec016bdad557d0c2bbc7bc8a5499ad6fedb6f144822fd29c",
                        "value": "2"
                      },
                      "type": {
                        "repr": "0x4abd7204bc024fbf9b78296fce94bc2b3ac71edb0f24b0d52d2268974a066316::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0xaf75cbf4e4115f4b723b5304461077b88db33bfff1aa24292c45612322bfd55b",
                        "value": "200"
                      },
                      "type": {
                        "repr": "0x4abd7204bc024fbf9b78296fce94bc2b3ac71edb0f24b0d52d2268974a066316::M1::Object"
                      }
                    }
                  }
                ]
              }
            },
            "gasPayment": {
              "nodes": [
                {
                  "asMoveObject": {
                    "contents": {
                      "type": {
                        "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0x0000000000000000000000000000000000000000000000000000000000000002::sui::SUI>"
                      },
                      "json": {
                        "id": "0x9b428e08aa9b65353e2ffce9231667f43e1bdbac51059739e40443cf1f497d70",
                        "balance": {
                          "value": "299999993044572"
                        }
                      }
                    }
                  }
                }
              ]
            }
          }
        }
      ]
    },
    "object_at_checkpoint_2": {
      "owner": {
        "owner": {
          "objects": {
            "nodes": [
              {
                "contents": {
                  "json": {
                    "id": "0x3ac686cdae3a9e3a5b0048844f7a33cc97aa72abe4ad4ad03e8de5b722d1bc33",
                    "value": "6"
                  },
                  "type": {
                    "repr": "0x4abd7204bc024fbf9b78296fce94bc2b3ac71edb0f24b0d52d2268974a066316::M1::Object"
                  }
                }
              },
              {
                "contents": {
                  "json": {
                    "id": "0x3ff04c623ee8dda6c2b5c0af65ac248cd07507e92b162c0b8f7702246f6c7bc8",
                    "value": "3"
                  },
                  "type": {
                    "repr": "0x4abd7204bc024fbf9b78296fce94bc2b3ac71edb0f24b0d52d2268974a066316::M1::Object"
                  }
                }
              },
              {
                "contents": {
                  "json": {
                    "id": "0x50cf0ec16e23b372376dea614904fd10eda1237c204baf4aac5109d4c8125d63",
                    "value": "5"
                  },
                  "type": {
                    "repr": "0x4abd7204bc024fbf9b78296fce94bc2b3ac71edb0f24b0d52d2268974a066316::M1::Object"
                  }
                }
              },
              {
                "contents": {
                  "json": {
                    "id": "0x58262f3e7d94e1cf1c6f77ac4498d2a1704bbde20b0b8f37a723426e43971c6b",
                    "value": "4"
                  },
                  "type": {
                    "repr": "0x4abd7204bc024fbf9b78296fce94bc2b3ac71edb0f24b0d52d2268974a066316::M1::Object"
                  }
                }
              },
              {
                "contents": {
                  "json": {
                    "id": "0xa20233cc7036333cec016bdad557d0c2bbc7bc8a5499ad6fedb6f144822fd29c",
                    "value": "2"
                  },
                  "type": {
                    "repr": "0x4abd7204bc024fbf9b78296fce94bc2b3ac71edb0f24b0d52d2268974a066316::M1::Object"
                  }
                }
              },
              {
                "contents": {
                  "json": {
                    "id": "0xaf75cbf4e4115f4b723b5304461077b88db33bfff1aa24292c45612322bfd55b",
                    "value": "200"
                  },
                  "type": {
                    "repr": "0x4abd7204bc024fbf9b78296fce94bc2b3ac71edb0f24b0d52d2268974a066316::M1::Object"
                  }
                }
              }
            ]
          }
        }
      }
    }
  }
}

task 11 'run-graphql'. lines 140-184:
Response: {
  "data": {
    "all_transactions": {
      "nodes": [
        {
          "sender": {
            "objects": {
              "nodes": [
                {
                  "contents": {
                    "json": {
                      "id": "0x3ac686cdae3a9e3a5b0048844f7a33cc97aa72abe4ad4ad03e8de5b722d1bc33",
                      "value": "6"
                    },
                    "type": {
                      "repr": "0x4abd7204bc024fbf9b78296fce94bc2b3ac71edb0f24b0d52d2268974a066316::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x3ff04c623ee8dda6c2b5c0af65ac248cd07507e92b162c0b8f7702246f6c7bc8",
                      "value": "3"
                    },
                    "type": {
                      "repr": "0x4abd7204bc024fbf9b78296fce94bc2b3ac71edb0f24b0d52d2268974a066316::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x50cf0ec16e23b372376dea614904fd10eda1237c204baf4aac5109d4c8125d63",
                      "value": "5"
                    },
                    "type": {
                      "repr": "0x4abd7204bc024fbf9b78296fce94bc2b3ac71edb0f24b0d52d2268974a066316::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x58262f3e7d94e1cf1c6f77ac4498d2a1704bbde20b0b8f37a723426e43971c6b",
                      "value": "4"
                    },
                    "type": {
                      "repr": "0x4abd7204bc024fbf9b78296fce94bc2b3ac71edb0f24b0d52d2268974a066316::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xa20233cc7036333cec016bdad557d0c2bbc7bc8a5499ad6fedb6f144822fd29c",
                      "value": "2"
                    },
                    "type": {
                      "repr": "0x4abd7204bc024fbf9b78296fce94bc2b3ac71edb0f24b0d52d2268974a066316::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xaf75cbf4e4115f4b723b5304461077b88db33bfff1aa24292c45612322bfd55b",
                      "value": "200"
                    },
                    "type": {
                      "repr": "0x4abd7204bc024fbf9b78296fce94bc2b3ac71edb0f24b0d52d2268974a066316::M1::Object"
                    }
                  }
                }
              ]
            }
          },
          "gasInput": {
            "gasSponsor": {
              "objects": {
                "nodes": [
                  {
                    "contents": {
                      "json": {
                        "id": "0xaf75cbf4e4115f4b723b5304461077b88db33bfff1aa24292c45612322bfd55b",
                        "value": "0"
                      },
                      "type": {
                        "repr": "0x4abd7204bc024fbf9b78296fce94bc2b3ac71edb0f24b0d52d2268974a066316::M1::Object"
                      }
                    }
                  }
                ]
              }
            },
            "gasPayment": {
              "nodes": [
                {
                  "asMoveObject": {
                    "contents": {
                      "type": {
                        "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0x0000000000000000000000000000000000000000000000000000000000000002::sui::SUI>"
                      },
                      "json": {
                        "id": "0x9b428e08aa9b65353e2ffce9231667f43e1bdbac51059739e40443cf1f497d70",
                        "balance": {
                          "value": "300000000000000"
                        }
                      }
                    }
                  }
                }
              ]
            }
          }
        },
        {
          "sender": {
            "objects": {
              "nodes": [
                {
                  "contents": {
                    "json": {
                      "id": "0x3ac686cdae3a9e3a5b0048844f7a33cc97aa72abe4ad4ad03e8de5b722d1bc33",
                      "value": "6"
                    },
                    "type": {
                      "repr": "0x4abd7204bc024fbf9b78296fce94bc2b3ac71edb0f24b0d52d2268974a066316::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x3ff04c623ee8dda6c2b5c0af65ac248cd07507e92b162c0b8f7702246f6c7bc8",
                      "value": "3"
                    },
                    "type": {
                      "repr": "0x4abd7204bc024fbf9b78296fce94bc2b3ac71edb0f24b0d52d2268974a066316::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x50cf0ec16e23b372376dea614904fd10eda1237c204baf4aac5109d4c8125d63",
                      "value": "5"
                    },
                    "type": {
                      "repr": "0x4abd7204bc024fbf9b78296fce94bc2b3ac71edb0f24b0d52d2268974a066316::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x58262f3e7d94e1cf1c6f77ac4498d2a1704bbde20b0b8f37a723426e43971c6b",
                      "value": "4"
                    },
                    "type": {
                      "repr": "0x4abd7204bc024fbf9b78296fce94bc2b3ac71edb0f24b0d52d2268974a066316::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xa20233cc7036333cec016bdad557d0c2bbc7bc8a5499ad6fedb6f144822fd29c",
                      "value": "2"
                    },
                    "type": {
                      "repr": "0x4abd7204bc024fbf9b78296fce94bc2b3ac71edb0f24b0d52d2268974a066316::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xaf75cbf4e4115f4b723b5304461077b88db33bfff1aa24292c45612322bfd55b",
                      "value": "200"
                    },
                    "type": {
                      "repr": "0x4abd7204bc024fbf9b78296fce94bc2b3ac71edb0f24b0d52d2268974a066316::M1::Object"
                    }
                  }
                }
              ]
            }
          },
          "gasInput": {
            "gasSponsor": {
              "objects": {
                "nodes": [
                  {
                    "contents": {
                      "json": {
                        "id": "0x3ff04c623ee8dda6c2b5c0af65ac248cd07507e92b162c0b8f7702246f6c7bc8",
                        "value": "3"
                      },
                      "type": {
                        "repr": "0x4abd7204bc024fbf9b78296fce94bc2b3ac71edb0f24b0d52d2268974a066316::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0xa20233cc7036333cec016bdad557d0c2bbc7bc8a5499ad6fedb6f144822fd29c",
                        "value": "2"
                      },
                      "type": {
                        "repr": "0x4abd7204bc024fbf9b78296fce94bc2b3ac71edb0f24b0d52d2268974a066316::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0xaf75cbf4e4115f4b723b5304461077b88db33bfff1aa24292c45612322bfd55b",
                        "value": "100"
                      },
                      "type": {
                        "repr": "0x4abd7204bc024fbf9b78296fce94bc2b3ac71edb0f24b0d52d2268974a066316::M1::Object"
                      }
                    }
                  }
                ]
              }
            },
            "gasPayment": {
              "nodes": [
                {
                  "asMoveObject": {
                    "contents": {
                      "type": {
                        "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0x0000000000000000000000000000000000000000000000000000000000000002::sui::SUI>"
                      },
                      "json": {
                        "id": "0x9b428e08aa9b65353e2ffce9231667f43e1bdbac51059739e40443cf1f497d70",
                        "balance": {
                          "value": "299999996697200"
                        }
                      }
                    }
                  }
                }
              ]
            }
          }
        },
        {
          "sender": {
            "objects": {
              "nodes": [
                {
                  "contents": {
                    "json": {
                      "id": "0x3ac686cdae3a9e3a5b0048844f7a33cc97aa72abe4ad4ad03e8de5b722d1bc33",
                      "value": "6"
                    },
                    "type": {
                      "repr": "0x4abd7204bc024fbf9b78296fce94bc2b3ac71edb0f24b0d52d2268974a066316::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x3ff04c623ee8dda6c2b5c0af65ac248cd07507e92b162c0b8f7702246f6c7bc8",
                      "value": "3"
                    },
                    "type": {
                      "repr": "0x4abd7204bc024fbf9b78296fce94bc2b3ac71edb0f24b0d52d2268974a066316::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x50cf0ec16e23b372376dea614904fd10eda1237c204baf4aac5109d4c8125d63",
                      "value": "5"
                    },
                    "type": {
                      "repr": "0x4abd7204bc024fbf9b78296fce94bc2b3ac71edb0f24b0d52d2268974a066316::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x58262f3e7d94e1cf1c6f77ac4498d2a1704bbde20b0b8f37a723426e43971c6b",
                      "value": "4"
                    },
                    "type": {
                      "repr": "0x4abd7204bc024fbf9b78296fce94bc2b3ac71edb0f24b0d52d2268974a066316::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xa20233cc7036333cec016bdad557d0c2bbc7bc8a5499ad6fedb6f144822fd29c",
                      "value": "2"
                    },
                    "type": {
                      "repr": "0x4abd7204bc024fbf9b78296fce94bc2b3ac71edb0f24b0d52d2268974a066316::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xaf75cbf4e4115f4b723b5304461077b88db33bfff1aa24292c45612322bfd55b",
                      "value": "200"
                    },
                    "type": {
                      "repr": "0x4abd7204bc024fbf9b78296fce94bc2b3ac71edb0f24b0d52d2268974a066316::M1::Object"
                    }
                  }
                }
              ]
            }
          },
          "gasInput": {
            "gasSponsor": {
              "objects": {
                "nodes": [
                  {
                    "contents": {
                      "json": {
                        "id": "0x3ac686cdae3a9e3a5b0048844f7a33cc97aa72abe4ad4ad03e8de5b722d1bc33",
                        "value": "6"
                      },
                      "type": {
                        "repr": "0x4abd7204bc024fbf9b78296fce94bc2b3ac71edb0f24b0d52d2268974a066316::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0x3ff04c623ee8dda6c2b5c0af65ac248cd07507e92b162c0b8f7702246f6c7bc8",
                        "value": "3"
                      },
                      "type": {
                        "repr": "0x4abd7204bc024fbf9b78296fce94bc2b3ac71edb0f24b0d52d2268974a066316::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0x50cf0ec16e23b372376dea614904fd10eda1237c204baf4aac5109d4c8125d63",
                        "value": "5"
                      },
                      "type": {
                        "repr": "0x4abd7204bc024fbf9b78296fce94bc2b3ac71edb0f24b0d52d2268974a066316::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0x58262f3e7d94e1cf1c6f77ac4498d2a1704bbde20b0b8f37a723426e43971c6b",
                        "value": "4"
                      },
                      "type": {
                        "repr": "0x4abd7204bc024fbf9b78296fce94bc2b3ac71edb0f24b0d52d2268974a066316::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0xa20233cc7036333cec016bdad557d0c2bbc7bc8a5499ad6fedb6f144822fd29c",
                        "value": "2"
                      },
                      "type": {
                        "repr": "0x4abd7204bc024fbf9b78296fce94bc2b3ac71edb0f24b0d52d2268974a066316::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0xaf75cbf4e4115f4b723b5304461077b88db33bfff1aa24292c45612322bfd55b",
                        "value": "200"
                      },
                      "type": {
                        "repr": "0x4abd7204bc024fbf9b78296fce94bc2b3ac71edb0f24b0d52d2268974a066316::M1::Object"
                      }
                    }
                  }
                ]
              }
            },
            "gasPayment": {
              "nodes": [
                {
                  "asMoveObject": {
                    "contents": {
                      "type": {
                        "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0x0000000000000000000000000000000000000000000000000000000000000002::sui::SUI>"
                      },
                      "json": {
                        "id": "0x9b428e08aa9b65353e2ffce9231667f43e1bdbac51059739e40443cf1f497d70",
                        "balance": {
                          "value": "299999993044572"
                        }
                      }
                    }
                  }
                }
              ]
            }
          }
        }
      ]
    }
  }
}

task 12 'force-object-snapshot-catchup'. lines 186-186:
Objects snapshot updated to [0 to 3)

task 13 'create-checkpoint'. lines 188-188:
Checkpoint created: 5

task 14 'run-graphql'. lines 190-264:
Response: {
  "data": {
    "address_at_latest_checkpoint_4": {
      "objects": {
        "nodes": [
          {
            "contents": {
              "json": {
                "id": "0x3ac686cdae3a9e3a5b0048844f7a33cc97aa72abe4ad4ad03e8de5b722d1bc33",
                "value": "6"
              },
              "type": {
                "repr": "0x4abd7204bc024fbf9b78296fce94bc2b3ac71edb0f24b0d52d2268974a066316::M1::Object"
              }
            }
          },
          {
            "contents": {
              "json": {
                "id": "0x3ff04c623ee8dda6c2b5c0af65ac248cd07507e92b162c0b8f7702246f6c7bc8",
                "value": "3"
              },
              "type": {
                "repr": "0x4abd7204bc024fbf9b78296fce94bc2b3ac71edb0f24b0d52d2268974a066316::M1::Object"
              }
            }
          },
          {
            "contents": {
              "json": {
                "id": "0x50cf0ec16e23b372376dea614904fd10eda1237c204baf4aac5109d4c8125d63",
                "value": "5"
              },
              "type": {
                "repr": "0x4abd7204bc024fbf9b78296fce94bc2b3ac71edb0f24b0d52d2268974a066316::M1::Object"
              }
            }
          },
          {
            "contents": {
              "json": {
                "id": "0x58262f3e7d94e1cf1c6f77ac4498d2a1704bbde20b0b8f37a723426e43971c6b",
                "value": "4"
              },
              "type": {
                "repr": "0x4abd7204bc024fbf9b78296fce94bc2b3ac71edb0f24b0d52d2268974a066316::M1::Object"
              }
            }
          },
          {
            "contents": {
              "json": {
                "id": "0xa20233cc7036333cec016bdad557d0c2bbc7bc8a5499ad6fedb6f144822fd29c",
                "value": "2"
              },
              "type": {
                "repr": "0x4abd7204bc024fbf9b78296fce94bc2b3ac71edb0f24b0d52d2268974a066316::M1::Object"
              }
            }
          },
          {
            "contents": {
              "json": {
                "id": "0xaf75cbf4e4115f4b723b5304461077b88db33bfff1aa24292c45612322bfd55b",
                "value": "200"
              },
              "type": {
                "repr": "0x4abd7204bc024fbf9b78296fce94bc2b3ac71edb0f24b0d52d2268974a066316::M1::Object"
              }
            }
          }
        ]
      }
    },
    "latest_tx_at_checkpoint_3": {
      "nodes": [
        {
          "sender": {
            "objects": {
              "nodes": [
                {
                  "contents": {
                    "json": {
                      "id": "0x3ac686cdae3a9e3a5b0048844f7a33cc97aa72abe4ad4ad03e8de5b722d1bc33",
                      "value": "6"
                    },
                    "type": {
                      "repr": "0x4abd7204bc024fbf9b78296fce94bc2b3ac71edb0f24b0d52d2268974a066316::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x3ff04c623ee8dda6c2b5c0af65ac248cd07507e92b162c0b8f7702246f6c7bc8",
                      "value": "3"
                    },
                    "type": {
                      "repr": "0x4abd7204bc024fbf9b78296fce94bc2b3ac71edb0f24b0d52d2268974a066316::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x50cf0ec16e23b372376dea614904fd10eda1237c204baf4aac5109d4c8125d63",
                      "value": "5"
                    },
                    "type": {
                      "repr": "0x4abd7204bc024fbf9b78296fce94bc2b3ac71edb0f24b0d52d2268974a066316::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x58262f3e7d94e1cf1c6f77ac4498d2a1704bbde20b0b8f37a723426e43971c6b",
                      "value": "4"
                    },
                    "type": {
                      "repr": "0x4abd7204bc024fbf9b78296fce94bc2b3ac71edb0f24b0d52d2268974a066316::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xa20233cc7036333cec016bdad557d0c2bbc7bc8a5499ad6fedb6f144822fd29c",
                      "value": "2"
                    },
                    "type": {
                      "repr": "0x4abd7204bc024fbf9b78296fce94bc2b3ac71edb0f24b0d52d2268974a066316::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xaf75cbf4e4115f4b723b5304461077b88db33bfff1aa24292c45612322bfd55b",
                      "value": "200"
                    },
                    "type": {
                      "repr": "0x4abd7204bc024fbf9b78296fce94bc2b3ac71edb0f24b0d52d2268974a066316::M1::Object"
                    }
                  }
                }
              ]
            }
          },
          "gasInput": {
            "gasSponsor": {
              "objects": {
                "nodes": [
                  {
                    "contents": {
                      "json": {
                        "id": "0x3ac686cdae3a9e3a5b0048844f7a33cc97aa72abe4ad4ad03e8de5b722d1bc33",
                        "value": "6"
                      },
                      "type": {
                        "repr": "0x4abd7204bc024fbf9b78296fce94bc2b3ac71edb0f24b0d52d2268974a066316::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0x3ff04c623ee8dda6c2b5c0af65ac248cd07507e92b162c0b8f7702246f6c7bc8",
                        "value": "3"
                      },
                      "type": {
                        "repr": "0x4abd7204bc024fbf9b78296fce94bc2b3ac71edb0f24b0d52d2268974a066316::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0x50cf0ec16e23b372376dea614904fd10eda1237c204baf4aac5109d4c8125d63",
                        "value": "5"
                      },
                      "type": {
                        "repr": "0x4abd7204bc024fbf9b78296fce94bc2b3ac71edb0f24b0d52d2268974a066316::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0x58262f3e7d94e1cf1c6f77ac4498d2a1704bbde20b0b8f37a723426e43971c6b",
                        "value": "4"
                      },
                      "type": {
                        "repr": "0x4abd7204bc024fbf9b78296fce94bc2b3ac71edb0f24b0d52d2268974a066316::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0xa20233cc7036333cec016bdad557d0c2bbc7bc8a5499ad6fedb6f144822fd29c",
                        "value": "2"
                      },
                      "type": {
                        "repr": "0x4abd7204bc024fbf9b78296fce94bc2b3ac71edb0f24b0d52d2268974a066316::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0xaf75cbf4e4115f4b723b5304461077b88db33bfff1aa24292c45612322bfd55b",
                        "value": "200"
                      },
                      "type": {
                        "repr": "0x4abd7204bc024fbf9b78296fce94bc2b3ac71edb0f24b0d52d2268974a066316::M1::Object"
                      }
                    }
                  }
                ]
              }
            },
            "gasPayment": {
              "nodes": [
                {
                  "asMoveObject": {
                    "contents": {
                      "type": {
                        "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0x0000000000000000000000000000000000000000000000000000000000000002::sui::SUI>"
                      },
                      "json": {
                        "id": "0x9b428e08aa9b65353e2ffce9231667f43e1bdbac51059739e40443cf1f497d70",
                        "balance": {
                          "value": "299999993044572"
                        }
                      }
                    }
                  }
                }
              ]
            }
          }
        }
      ]
    },
    "object_at_checkpoint_2": {
      "owner": {
        "owner": {
          "objects": {
            "nodes": [
              {
                "contents": {
                  "json": {
                    "id": "0x3ac686cdae3a9e3a5b0048844f7a33cc97aa72abe4ad4ad03e8de5b722d1bc33",
                    "value": "6"
                  },
                  "type": {
                    "repr": "0x4abd7204bc024fbf9b78296fce94bc2b3ac71edb0f24b0d52d2268974a066316::M1::Object"
                  }
                }
              },
              {
                "contents": {
                  "json": {
                    "id": "0x3ff04c623ee8dda6c2b5c0af65ac248cd07507e92b162c0b8f7702246f6c7bc8",
                    "value": "3"
                  },
                  "type": {
                    "repr": "0x4abd7204bc024fbf9b78296fce94bc2b3ac71edb0f24b0d52d2268974a066316::M1::Object"
                  }
                }
              },
              {
                "contents": {
                  "json": {
                    "id": "0x50cf0ec16e23b372376dea614904fd10eda1237c204baf4aac5109d4c8125d63",
                    "value": "5"
                  },
                  "type": {
                    "repr": "0x4abd7204bc024fbf9b78296fce94bc2b3ac71edb0f24b0d52d2268974a066316::M1::Object"
                  }
                }
              },
              {
                "contents": {
                  "json": {
                    "id": "0x58262f3e7d94e1cf1c6f77ac4498d2a1704bbde20b0b8f37a723426e43971c6b",
                    "value": "4"
                  },
                  "type": {
                    "repr": "0x4abd7204bc024fbf9b78296fce94bc2b3ac71edb0f24b0d52d2268974a066316::M1::Object"
                  }
                }
              },
              {
                "contents": {
                  "json": {
                    "id": "0xa20233cc7036333cec016bdad557d0c2bbc7bc8a5499ad6fedb6f144822fd29c",
                    "value": "2"
                  },
                  "type": {
                    "repr": "0x4abd7204bc024fbf9b78296fce94bc2b3ac71edb0f24b0d52d2268974a066316::M1::Object"
                  }
                }
              },
              {
                "contents": {
                  "json": {
                    "id": "0xaf75cbf4e4115f4b723b5304461077b88db33bfff1aa24292c45612322bfd55b",
                    "value": "200"
                  },
                  "type": {
                    "repr": "0x4abd7204bc024fbf9b78296fce94bc2b3ac71edb0f24b0d52d2268974a066316::M1::Object"
                  }
                }
              }
            ]
          }
        }
      }
    }
  }
}

task 15 'create-checkpoint'. lines 266-266:
Checkpoint created: 6

task 16 'run-graphql'. lines 268-303:
Response: {
  "data": {
    "all_transactions": {
      "nodes": [
        {
          "sender": {
            "objects": {
              "nodes": [
                {
                  "contents": {
                    "json": {
                      "id": "0x3ac686cdae3a9e3a5b0048844f7a33cc97aa72abe4ad4ad03e8de5b722d1bc33",
                      "value": "6"
                    },
                    "type": {
                      "repr": "0x4abd7204bc024fbf9b78296fce94bc2b3ac71edb0f24b0d52d2268974a066316::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x3ff04c623ee8dda6c2b5c0af65ac248cd07507e92b162c0b8f7702246f6c7bc8",
                      "value": "3"
                    },
                    "type": {
                      "repr": "0x4abd7204bc024fbf9b78296fce94bc2b3ac71edb0f24b0d52d2268974a066316::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x50cf0ec16e23b372376dea614904fd10eda1237c204baf4aac5109d4c8125d63",
                      "value": "5"
                    },
                    "type": {
                      "repr": "0x4abd7204bc024fbf9b78296fce94bc2b3ac71edb0f24b0d52d2268974a066316::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x58262f3e7d94e1cf1c6f77ac4498d2a1704bbde20b0b8f37a723426e43971c6b",
                      "value": "4"
                    },
                    "type": {
                      "repr": "0x4abd7204bc024fbf9b78296fce94bc2b3ac71edb0f24b0d52d2268974a066316::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xa20233cc7036333cec016bdad557d0c2bbc7bc8a5499ad6fedb6f144822fd29c",
                      "value": "2"
                    },
                    "type": {
                      "repr": "0x4abd7204bc024fbf9b78296fce94bc2b3ac71edb0f24b0d52d2268974a066316::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xaf75cbf4e4115f4b723b5304461077b88db33bfff1aa24292c45612322bfd55b",
                      "value": "200"
                    },
                    "type": {
                      "repr": "0x4abd7204bc024fbf9b78296fce94bc2b3ac71edb0f24b0d52d2268974a066316::M1::Object"
                    }
                  }
                }
              ]
            }
          },
          "gasInput": {
            "gasSponsor": null
          }
        },
        {
          "sender": {
            "objects": {
              "nodes": [
                {
                  "contents": {
                    "json": {
                      "id": "0x3ac686cdae3a9e3a5b0048844f7a33cc97aa72abe4ad4ad03e8de5b722d1bc33",
                      "value": "6"
                    },
                    "type": {
                      "repr": "0x4abd7204bc024fbf9b78296fce94bc2b3ac71edb0f24b0d52d2268974a066316::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x3ff04c623ee8dda6c2b5c0af65ac248cd07507e92b162c0b8f7702246f6c7bc8",
                      "value": "3"
                    },
                    "type": {
                      "repr": "0x4abd7204bc024fbf9b78296fce94bc2b3ac71edb0f24b0d52d2268974a066316::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x50cf0ec16e23b372376dea614904fd10eda1237c204baf4aac5109d4c8125d63",
                      "value": "5"
                    },
                    "type": {
                      "repr": "0x4abd7204bc024fbf9b78296fce94bc2b3ac71edb0f24b0d52d2268974a066316::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x58262f3e7d94e1cf1c6f77ac4498d2a1704bbde20b0b8f37a723426e43971c6b",
                      "value": "4"
                    },
                    "type": {
                      "repr": "0x4abd7204bc024fbf9b78296fce94bc2b3ac71edb0f24b0d52d2268974a066316::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xa20233cc7036333cec016bdad557d0c2bbc7bc8a5499ad6fedb6f144822fd29c",
                      "value": "2"
                    },
                    "type": {
                      "repr": "0x4abd7204bc024fbf9b78296fce94bc2b3ac71edb0f24b0d52d2268974a066316::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xaf75cbf4e4115f4b723b5304461077b88db33bfff1aa24292c45612322bfd55b",
                      "value": "200"
                    },
                    "type": {
                      "repr": "0x4abd7204bc024fbf9b78296fce94bc2b3ac71edb0f24b0d52d2268974a066316::M1::Object"
                    }
                  }
                }
              ]
            }
          },
          "gasInput": {
            "gasSponsor": {
              "objects": {
                "nodes": [
                  {
                    "contents": {
                      "json": {
                        "id": "0x3ff04c623ee8dda6c2b5c0af65ac248cd07507e92b162c0b8f7702246f6c7bc8",
                        "value": "3"
                      },
                      "type": {
                        "repr": "0x4abd7204bc024fbf9b78296fce94bc2b3ac71edb0f24b0d52d2268974a066316::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0xa20233cc7036333cec016bdad557d0c2bbc7bc8a5499ad6fedb6f144822fd29c",
                        "value": "2"
                      },
                      "type": {
                        "repr": "0x4abd7204bc024fbf9b78296fce94bc2b3ac71edb0f24b0d52d2268974a066316::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0xaf75cbf4e4115f4b723b5304461077b88db33bfff1aa24292c45612322bfd55b",
                        "value": "100"
                      },
                      "type": {
                        "repr": "0x4abd7204bc024fbf9b78296fce94bc2b3ac71edb0f24b0d52d2268974a066316::M1::Object"
                      }
                    }
                  }
                ]
              }
            }
          }
        },
        {
          "sender": {
            "objects": {
              "nodes": [
                {
                  "contents": {
                    "json": {
                      "id": "0x3ac686cdae3a9e3a5b0048844f7a33cc97aa72abe4ad4ad03e8de5b722d1bc33",
                      "value": "6"
                    },
                    "type": {
                      "repr": "0x4abd7204bc024fbf9b78296fce94bc2b3ac71edb0f24b0d52d2268974a066316::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x3ff04c623ee8dda6c2b5c0af65ac248cd07507e92b162c0b8f7702246f6c7bc8",
                      "value": "3"
                    },
                    "type": {
                      "repr": "0x4abd7204bc024fbf9b78296fce94bc2b3ac71edb0f24b0d52d2268974a066316::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x50cf0ec16e23b372376dea614904fd10eda1237c204baf4aac5109d4c8125d63",
                      "value": "5"
                    },
                    "type": {
                      "repr": "0x4abd7204bc024fbf9b78296fce94bc2b3ac71edb0f24b0d52d2268974a066316::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x58262f3e7d94e1cf1c6f77ac4498d2a1704bbde20b0b8f37a723426e43971c6b",
                      "value": "4"
                    },
                    "type": {
                      "repr": "0x4abd7204bc024fbf9b78296fce94bc2b3ac71edb0f24b0d52d2268974a066316::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xa20233cc7036333cec016bdad557d0c2bbc7bc8a5499ad6fedb6f144822fd29c",
                      "value": "2"
                    },
                    "type": {
                      "repr": "0x4abd7204bc024fbf9b78296fce94bc2b3ac71edb0f24b0d52d2268974a066316::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xaf75cbf4e4115f4b723b5304461077b88db33bfff1aa24292c45612322bfd55b",
                      "value": "200"
                    },
                    "type": {
                      "repr": "0x4abd7204bc024fbf9b78296fce94bc2b3ac71edb0f24b0d52d2268974a066316::M1::Object"
                    }
                  }
                }
              ]
            }
          },
          "gasInput": {
            "gasSponsor": {
              "objects": {
                "nodes": [
                  {
                    "contents": {
                      "json": {
                        "id": "0x3ac686cdae3a9e3a5b0048844f7a33cc97aa72abe4ad4ad03e8de5b722d1bc33",
                        "value": "6"
                      },
                      "type": {
                        "repr": "0x4abd7204bc024fbf9b78296fce94bc2b3ac71edb0f24b0d52d2268974a066316::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0x3ff04c623ee8dda6c2b5c0af65ac248cd07507e92b162c0b8f7702246f6c7bc8",
                        "value": "3"
                      },
                      "type": {
                        "repr": "0x4abd7204bc024fbf9b78296fce94bc2b3ac71edb0f24b0d52d2268974a066316::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0x50cf0ec16e23b372376dea614904fd10eda1237c204baf4aac5109d4c8125d63",
                        "value": "5"
                      },
                      "type": {
                        "repr": "0x4abd7204bc024fbf9b78296fce94bc2b3ac71edb0f24b0d52d2268974a066316::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0x58262f3e7d94e1cf1c6f77ac4498d2a1704bbde20b0b8f37a723426e43971c6b",
                        "value": "4"
                      },
                      "type": {
                        "repr": "0x4abd7204bc024fbf9b78296fce94bc2b3ac71edb0f24b0d52d2268974a066316::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0xa20233cc7036333cec016bdad557d0c2bbc7bc8a5499ad6fedb6f144822fd29c",
                        "value": "2"
                      },
                      "type": {
                        "repr": "0x4abd7204bc024fbf9b78296fce94bc2b3ac71edb0f24b0d52d2268974a066316::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0xaf75cbf4e4115f4b723b5304461077b88db33bfff1aa24292c45612322bfd55b",
                        "value": "200"
                      },
                      "type": {
                        "repr": "0x4abd7204bc024fbf9b78296fce94bc2b3ac71edb0f24b0d52d2268974a066316::M1::Object"
                      }
                    }
                  }
                ]
              }
            }
          }
        }
      ]
    }
  },
  "errors": [
    {
      "message": "Requested data is outside the available range",
      "locations": [
        {
          "line": 21,
          "column": 11
        }
      ],
      "path": [
        "all_transactions",
        "nodes",
        0,
        "gasInput",
        "gasSponsor",
        "objects"
      ],
      "extensions": {
        "code": "BAD_USER_INPUT"
      }
    }
  ]
}
