processed 16 tasks

init:
A: object(0,0), B: object(0,1)

task 1 'publish'. lines 13-30:
created: object(1,0)
mutated: object(0,2)
gas summary: computation_cost: 1000000, storage_cost: 5175600,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2 'run'. lines 32-32:
created: object(2,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 0, non_refundable_storage_fee: 0

task 3 'run'. lines 34-34:
created: object(3,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 978120, non_refundable_storage_fee: 9880

task 4 'run'. lines 36-36:
created: object(4,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 978120, non_refundable_storage_fee: 9880

task 5 'run'. lines 38-38:
created: object(5,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 978120, non_refundable_storage_fee: 9880

task 6 'create-checkpoint'. lines 40-40:
Checkpoint created: 1

task 7 'run'. lines 42-42:
created: object(7,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 978120, non_refundable_storage_fee: 9880

task 8 'run'. lines 44-44:
created: object(8,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 978120, non_refundable_storage_fee: 9880

task 9 'run'. lines 46-46:
created: object(9,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 978120, non_refundable_storage_fee: 9880

task 10 'create-checkpoint'. lines 48-48:
Checkpoint created: 2

task 11 'run'. lines 50-50:
created: object(11,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 978120, non_refundable_storage_fee: 9880

task 12 'run'. lines 52-52:
created: object(12,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 978120, non_refundable_storage_fee: 9880

task 13 'create-checkpoint'. lines 54-54:
Checkpoint created: 3

task 14 'run-graphql'. lines 56-80:
Response: {
  "data": {
    "checkpoints": {
      "nodes": [
        {
          "sequenceNumber": 0,
          "transactionBlocks": {
            "edges": []
          }
        },
        {
          "sequenceNumber": 1,
          "transactionBlocks": {
            "edges": [
              {
                "cursor": "eyJjIjozLCJ0IjoyLCJ0YyI6MX0",
                "node": {
                  "digest": "33MGxJvs6rGC2Z9dKYahHWSr5gcSKJRMvq9rLjNcZE1S",
                  "sender": {
                    "objects": {
                      "edges": [
                        {
                          "cursor": "IOQuDc26gUFyjBWhA8ZXcwAC4XIysmCKSTVONtvXjiCXAwAAAAAAAAA="
                        }
                      ]
                    }
                  }
                }
              },
              {
                "cursor": "eyJjIjozLCJ0IjozLCJ0YyI6MX0",
                "node": {
                  "digest": "8EZomHLKmZwTCgRsSYdKMp4BfCdGJWCcJgeigWAVqQTi",
                  "sender": {
                    "objects": {
                      "edges": [
                        {
                          "cursor": "IOQuDc26gUFyjBWhA8ZXcwAC4XIysmCKSTVONtvXjiCXAwAAAAAAAAA="
                        }
                      ]
                    }
                  }
                }
              },
              {
                "cursor": "eyJjIjozLCJ0Ijo0LCJ0YyI6MX0",
                "node": {
                  "digest": "5bV5KFezvwEpbbg3CtghoJgX2dkaYpKRzo1FB34cgwPD",
                  "sender": {
                    "objects": {
                      "edges": [
                        {
                          "cursor": "IOQuDc26gUFyjBWhA8ZXcwAC4XIysmCKSTVONtvXjiCXAwAAAAAAAAA="
                        }
                      ]
                    }
                  }
                }
              },
              {
                "cursor": "eyJjIjozLCJ0Ijo1LCJ0YyI6MX0",
                "node": {
                  "digest": "D6jYgwNWi5MssspyCednXW3gJ6g2xzaLFEJjqCW6tWF8",
                  "sender": {
                    "objects": {
                      "edges": [
                        {
                          "cursor": "IOQuDc26gUFyjBWhA8ZXcwAC4XIysmCKSTVONtvXjiCXAwAAAAAAAAA="
                        }
                      ]
                    }
                  }
                }
              }
            ]
          }
        },
        {
          "sequenceNumber": 2,
          "transactionBlocks": {
            "edges": [
              {
                "cursor": "eyJjIjozLCJ0Ijo2LCJ0YyI6Mn0",
                "node": {
                  "digest": "BhraPGfNFYJJVthPV1bai3Zk4yzu3KyhKeTbs1NFmF6j",
                  "sender": {
                    "objects": {
                      "edges": [
                        {
                          "cursor": "IOQuDc26gUFyjBWhA8ZXcwAC4XIysmCKSTVONtvXjiCXAwAAAAAAAAA="
                        }
                      ]
                    }
                  }
                }
              },
              {
                "cursor": "eyJjIjozLCJ0Ijo3LCJ0YyI6Mn0",
                "node": {
                  "digest": "AaqkG3nqU83GNN5X9MKfWsS2Q5MPrjhdnuM6ehoCLQKM",
                  "sender": {
                    "objects": {
                      "edges": [
                        {
                          "cursor": "IOQuDc26gUFyjBWhA8ZXcwAC4XIysmCKSTVONtvXjiCXAwAAAAAAAAA="
                        }
                      ]
                    }
                  }
                }
              },
              {
                "cursor": "eyJjIjozLCJ0Ijo4LCJ0YyI6Mn0",
                "node": {
                  "digest": "2shvr4hYDA7rvowLzXPik9n5k3eHxfCwawsrWpFBg5Ts",
                  "sender": {
                    "objects": {
                      "edges": [
                        {
                          "cursor": "IOQuDc26gUFyjBWhA8ZXcwAC4XIysmCKSTVONtvXjiCXAwAAAAAAAAA="
                        }
                      ]
                    }
                  }
                }
              }
            ]
          }
        },
        {
          "sequenceNumber": 3,
          "transactionBlocks": {
            "edges": [
              {
                "cursor": "eyJjIjozLCJ0Ijo5LCJ0YyI6M30",
                "node": {
                  "digest": "HpmAZzQxkchd5rnr1MFpWrnsyQKpeSsLLBEKKAM6RHNX",
                  "sender": {
                    "objects": {
                      "edges": [
                        {
                          "cursor": "IOQuDc26gUFyjBWhA8ZXcwAC4XIysmCKSTVONtvXjiCXAwAAAAAAAAA="
                        }
                      ]
                    }
                  }
                }
              },
              {
                "cursor": "eyJjIjozLCJ0IjoxMCwidGMiOjN9",
                "node": {
                  "digest": "8iggMZnQbhHYa9XHUpcaX92qsGHFRwD3M2TFnuvke5fu",
                  "sender": {
                    "objects": {
                      "edges": [
                        {
                          "cursor": "IOQuDc26gUFyjBWhA8ZXcwAC4XIysmCKSTVONtvXjiCXAwAAAAAAAAA="
                        }
                      ]
                    }
                  }
                }
              }
            ]
          }
        }
      ]
    }
  }
}

task 15 'run-graphql'. lines 82-99:
Response: {
  "data": {
    "checkpoints": {
      "nodes": [
        {
          "sequenceNumber": 0,
          "epoch": {
            "epochId": 0,
            "checkpoints": {
              "nodes": [
                {
                  "sequenceNumber": 0
                },
                {
                  "sequenceNumber": 1
                },
                {
                  "sequenceNumber": 2
                },
                {
                  "sequenceNumber": 3
                }
              ]
            }
          }
        },
        {
          "sequenceNumber": 1,
          "epoch": {
            "epochId": 0,
            "checkpoints": {
              "nodes": [
                {
                  "sequenceNumber": 0
                },
                {
                  "sequenceNumber": 1
                },
                {
                  "sequenceNumber": 2
                },
                {
                  "sequenceNumber": 3
                }
              ]
            }
          }
        },
        {
          "sequenceNumber": 2,
          "epoch": {
            "epochId": 0,
            "checkpoints": {
              "nodes": [
                {
                  "sequenceNumber": 0
                },
                {
                  "sequenceNumber": 1
                },
                {
                  "sequenceNumber": 2
                },
                {
                  "sequenceNumber": 3
                }
              ]
            }
          }
        },
        {
          "sequenceNumber": 3,
          "epoch": {
            "epochId": 0,
            "checkpoints": {
              "nodes": [
                {
                  "sequenceNumber": 0
                },
                {
                  "sequenceNumber": 1
                },
                {
                  "sequenceNumber": 2
                },
                {
                  "sequenceNumber": 3
                }
              ]
            }
          }
        }
      ]
    }
  }
}
