processed 4 tasks

init:
A: object(0,0)

task 1 'publish'. lines 6-35:
created: object(1,0), object(1,1), object(1,2), object(1,3), object(1,4), object(1,5)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 15663600,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2 'create-checkpoint'. lines 37-37:
Checkpoint created: 1

task 3 'run-graphql'. lines 39-87:
Response: {
  "data": {
    "suiCoins": {
      "edges": [
        {
          "cursor": "IINAUKeknpx7fCr0uYvdoBLKnjVtZcJ0JmBx5hPwUw/8AQAAAAAAAAA=",
          "node": {
            "coinBalance": "299999983336400",
            "contents": {
              "type": {
                "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0x0000000000000000000000000000000000000000000000000000000000000002::sui::SUI>"
              }
            }
          }
        },
        {
          "cursor": "IKM32uqZmRsXr6UkuEvJFDzmDCIdhMuuAy3b7wQarDOHAQAAAAAAAAA=",
          "node": {
            "coinBalance": "300000000000000",
            "contents": {
              "type": {
                "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0x0000000000000000000000000000000000000000000000000000000000000002::sui::SUI>"
              }
            }
          }
        },
        {
          "cursor": "IPvb+iWqZcgjxchPk+dnvQ3LC++MDms12ct5NkZPcOhUAQAAAAAAAAA=",
          "node": {
            "coinBalance": "30000000000000000",
            "contents": {
              "type": {
                "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0x0000000000000000000000000000000000000000000000000000000000000002::sui::SUI>"
              }
            }
          }
        }
      ]
    },
    "fakeCoins": {
      "edges": [
        {
          "cursor": "IBWS70H0u56Dosiv0eVNROsFac3T1/YAk56FcMyhGSLzAQAAAAAAAAA=",
          "node": {
            "coinBalance": "2",
            "contents": {
              "type": {
                "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0x03b84f3dea921c1696a9582dc956fe7d34f67cd3b5644cdee1a2670d3d61830f::fake::FAKE>"
              }
            }
          }
        },
        {
          "cursor": "IDmjV+MT11rjFO/WIqDK+gDT5IMfv1VrQ9fVjLVF+CrSAQAAAAAAAAA=",
          "node": {
            "coinBalance": "1",
            "contents": {
              "type": {
                "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0x03b84f3dea921c1696a9582dc956fe7d34f67cd3b5644cdee1a2670d3d61830f::fake::FAKE>"
              }
            }
          }
        },
        {
          "cursor": "IJ5trROWF1g0meMskGzUXzm4joa5Z0FZ9NH6J+1rvOJpAQAAAAAAAAA=",
          "node": {
            "coinBalance": "3",
            "contents": {
              "type": {
                "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0x03b84f3dea921c1696a9582dc956fe7d34f67cd3b5644cdee1a2670d3d61830f::fake::FAKE>"
              }
            }
          }
        }
      ]
    },
    "address": {
      "coins": {
        "edges": [
          {
            "cursor": "IINAUKeknpx7fCr0uYvdoBLKnjVtZcJ0JmBx5hPwUw/8AQAAAAAAAAA=",
            "node": {
              "coinBalance": "299999983336400",
              "contents": {
                "type": {
                  "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0x0000000000000000000000000000000000000000000000000000000000000002::sui::SUI>"
                }
              }
            }
          }
        ]
      },
      "allBalances": {
        "edges": [
          {
            "cursor": "eyJ0IjoiMHgwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAyOjpzdWk6OlNVSSIsImMiOjF9",
            "node": {
              "coinType": {
                "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::sui::SUI"
              },
              "coinObjectCount": 1,
              "totalBalance": "299999983336400"
            }
          },
          {
            "cursor": "eyJ0IjoiMHgwM2I4NGYzZGVhOTIxYzE2OTZhOTU4MmRjOTU2ZmU3ZDM0ZjY3Y2QzYjU2NDRjZGVlMWEyNjcwZDNkNjE4MzBmOjpmYWtlOjpGQUtFIiwiYyI6MX0",
            "node": {
              "coinType": {
                "repr": "0x03b84f3dea921c1696a9582dc956fe7d34f67cd3b5644cdee1a2670d3d61830f::fake::FAKE"
              },
              "coinObjectCount": 3,
              "totalBalance": "6"
            }
          }
        ]
      },
      "firstBalance": {
        "edges": [
          {
            "cursor": "eyJ0IjoiMHgwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAyOjpzdWk6OlNVSSIsImMiOjF9"
          }
        ]
      },
      "lastBalance": {
        "edges": [
          {
            "cursor": "eyJ0IjoiMHgwM2I4NGYzZGVhOTIxYzE2OTZhOTU4MmRjOTU2ZmU3ZDM0ZjY3Y2QzYjU2NDRjZGVlMWEyNjcwZDNkNjE4MzBmOjpmYWtlOjpGQUtFIiwiYyI6MX0"
          }
        ]
      }
    }
  }
}
