processed 5 tasks

init:
A: object(0,0)

task 1 'publish'. lines 6-41:
created: object(1,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 7622800,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2 'programmable'. lines 43-45:
created: object(2,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 2910800,  storage_rebate: 978120, non_refundable_storage_fee: 9880

task 3 'create-checkpoint'. lines 47-47:
Checkpoint created: 1

task 4 'run-graphql'. lines 49-70:
Response: {
  "data": {
    "transactionBlocks": {
      "nodes": [
        {
          "effects": {
            "objectChanges": {
              "nodes": [
                {
                  "outputState": {
                    "asMoveObject": {
                      "contents": {
                        "type": {
                          "repr": "0xeeb395321980aa0168161d899586567da3ed96cf7b3f725fdc1ccecf9a00baae::m::Foo"
                        },
                        "data": {
                          "Struct": [
                            {
                              "name": "id",
                              "value": {
                                "UID": [
                                  129,
                                  114,
                                  119,
                                  137,
                                  153,
                                  144,
                                  133,
                                  155,
                                  160,
                                  131,
                                  30,
                                  248,
                                  159,
                                  141,
                                  222,
                                  185,
                                  253,
                                  120,
                                  147,
                                  226,
                                  96,
                                  195,
                                  209,
                                  205,
                                  159,
                                  42,
                                  152,
                                  0,
                                  3,
                                  138,
                                  125,
                                  175
                                ]
                              }
                            },
                            {
                              "name": "f0",
                              "value": {
                                "ID": [
                                  129,
                                  114,
                                  119,
                                  137,
                                  153,
                                  144,
                                  133,
                                  155,
                                  160,
                                  131,
                                  30,
                                  248,
                                  159,
                                  141,
                                  222,
                                  185,
                                  253,
                                  120,
                                  147,
                                  226,
                                  96,
                                  195,
                                  209,
                                  205,
                                  159,
                                  42,
                                  152,
                                  0,
                                  3,
                                  138,
                                  125,
                                  175
                                ]
                              }
                            },
                            {
                              "name": "f1",
                              "value": {
                                "Bool": true
                              }
                            },
                            {
                              "name": "f2",
                              "value": {
                                "Number": "42"
                              }
                            },
                            {
                              "name": "f3",
                              "value": {
                                "Number": "43"
                              }
                            },
                            {
                              "name": "f4",
                              "value": {
                                "String": "hello"
                              }
                            },
                            {
                              "name": "f5",
                              "value": {
                                "String": "world"
                              }
                            },
                            {
                              "name": "f6",
                              "value": {
                                "Vector": [
                                  {
                                    "Address": [
                                      129,
                                      114,
                                      119,
                                      137,
                                      153,
                                      144,
                                      133,
                                      155,
                                      160,
                                      131,
                                      30,
                                      248,
                                      159,
                                      141,
                                      222,
                                      185,
                                      253,
                                      120,
                                      147,
                                      226,
                                      96,
                                      195,
                                      209,
                                      205,
                                      159,
                                      42,
                                      152,
                                      0,
                                      3,
                                      138,
                                      125,
                                      175
                                    ]
                                  }
                                ]
                              }
                            },
                            {
                              "name": "f7",
                              "value": {
                                "Option": {
                                  "Number": "44"
                                }
                              }
                            }
                          ]
                        },
                        "json": {
                          "id": "0x817277899990859ba0831ef89f8ddeb9fd7893e260c3d1cd9f2a9800038a7daf",
                          "f0": "0x817277899990859ba0831ef89f8ddeb9fd7893e260c3d1cd9f2a9800038a7daf",
                          "f1": true,
                          "f2": 42,
                          "f3": "43",
                          "f4": "hello",
                          "f5": "world",
                          "f6": [
                            "0x817277899990859ba0831ef89f8ddeb9fd7893e260c3d1cd9f2a9800038a7daf"
                          ],
                          "f7": 44
                        }
                      }
                    }
                  }
                },
                {
                  "outputState": {
                    "asMoveObject": {
                      "contents": {
                        "type": {
                          "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0x0000000000000000000000000000000000000000000000000000000000000002::sui::SUI>"
                        },
                        "data": {
                          "Struct": [
                            {
                              "name": "id",
                              "value": {
                                "UID": [
                                  163,
                                  55,
                                  218,
                                  234,
                                  153,
                                  153,
                                  27,
                                  23,
                                  175,
                                  165,
                                  36,
                                  184,
                                  75,
                                  201,
                                  20,
                                  60,
                                  230,
                                  12,
                                  34,
                                  29,
                                  132,
                                  203,
                                  174,
                                  3,
                                  45,
                                  219,
                                  239,
                                  4,
                                  26,
                                  172,
                                  51,
                                  135
                                ]
                              }
                            },
                            {
                              "name": "balance",
                              "value": {
                                "Struct": [
                                  {
                                    "name": "value",
                                    "value": {
                                      "Number": "299999988444520"
                                    }
                                  }
                                ]
                              }
                            }
                          ]
                        },
                        "json": {
                          "id": "0xa337daea99991b17afa524b84bc9143ce60c221d84cbae032ddbef041aac3387",
                          "balance": {
                            "value": "299999988444520"
                          }
                        }
                      }
                    }
                  }
                }
              ]
            }
          }
        }
      ]
    }
  }
}
